# INTRODUCTION (Main Questions)

This is the data analysis notebook for CSE 8B Winter 2020


<hr> 

## <a id='toc'>Table of Contents </a>

- [Setting up data](#section_sud)
- [Basic Cleaning data](#section_2)
- <b> [General Functions](#section_general_functions)</b> 
- [Missing Data Explanation](#section_missing_data)
- [How We Handle Outliers](#section_outlier) 
- [List of Dataframes](#section_dfs)
- [General Mean Functions](#section_funcs_mean) 
- <b> [Research Question Start (On Hours spent outside of class)](#section_RQ1) </b> 
- [Research Question - Hours Spent Outside of Class Graphs](#section_RQ1_graphs) </b> 
- [Research Question Conclusion (On Hours spent outside of class)](#section_RQ1_conclusion) </b> 
- <b> [Research Question Start (On Overall Grades)](#section_RQG) </b> 
- [Research Question - Overall Grades Graphs](#section_RQG_graphs) </b> 
- [Research Question Conclusion (On Overall Grades )](#section_RQG_conclusion) </b> 
- <b> [Research Question Start (On Confidence Level)](#section_RQC) </b> 
- [Research Question Conclusion (On Confidence Level )](#section_RQC_conclusion) </b> 
- <b> [Interview Questions](#section_interview) </b> 

<hr>



### <a id='section_sud'> Loading Data CSVs </a> 


In [20]:

# from google.colab import drive
# drive.mount('/content/drive',force_remount=True)

# # drive.flush_and_unmount()


In [21]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import seaborn as sns
import csv  
import math
from scipy.stats import ttest_ind


%matplotlib inline
%config InlineBackend.figure_format = 'retina'  # Higher resolution figures
# set defaults
plt.style.use('seaborn-white')   # seaborn custom plot style
plt.rc('figure', dpi=100, figsize=(7, 5))   # set default size/resolution
plt.rc('font', size=12)   # font size

#importing the data files in colab
#presurvey and demographics
# df = pd.read_csv(('/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/presurvey.csv'))
# df_d = pd.read_csv(('/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/CSE_Alvarado_WI20_Demographics.csv'))

# df_gradesA_B = pd.read_csv("/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/DeID PID_CSE 8B Grades Sec A_B.csv")
# df_gradesC_D = pd.read_csv("/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/DeID PID_CSE 8B Grades Sec C_D.csv")

# df_gradesB = pd.read_csv("/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/DeID PID_2020-04-06T1449_Grades-CSE8B_WI20_B00.csv")
# df_gradesC = pd.read_csv("/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/DeID PID_2020-04-06T1429_Grades-CSE8B_WI20_C00.csv")

#weekly reflection
# df_w1 = pd.read_csv(('/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/R1.csv'))
# df_w2 = pd.read_csv(('/content/drive/Shared drives/CERSummerResearch/cse8a_winter2020_data/R2.csv'))
# df_w3 = pd.read_csv(('/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/R3.csv'))
# df_w4 = pd.read_csv(('/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/R4.csv'))
# df_w5 = pd.read_csv(('/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/R5.csv'))
# df_w6 = pd.read_csv(('/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/R6.csv'))
# df_w7 = pd.read_csv(('/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/R7.csv'))
# df_w8 = pd.read_csv(('/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/R8.csv'))
# df_w9 = pd.read_csv(('/content/drive/Shared drives/CERSummerResearch/cse8b_winter2020_data/R9.csv'))

#importing the data files in jupyter
df = pd.read_csv(('presurvey.csv'))
df_d = pd.read_csv(('CSE_Alvarado_WI20_Demographics.csv'))
df_d = df_d.rename(columns={"Gender(Binary)": "gender"})

df_gradesA_B = pd.read_csv("DeID PID_CSE 8B Grades Sec A_B.csv")
df_gradesC_D = pd.read_csv("DeID PID_CSE 8B Grades Sec C_D.csv")
df_gradesB = pd.read_csv("DeID PID_2020-04-06T1449_Grades-CSE8B_WI20_B00.csv")
df_gradesC = pd.read_csv("DeID PID_2020-04-06T1429_Grades-CSE8B_WI20_C00.csv")
df_w1 = pd.read_csv(('R1.csv'))
df_w2 = pd.read_csv(('R2.csv'))
df_w3 = pd.read_csv(('R3.csv'))
df_w4 = pd.read_csv(('R4.csv'))
df_w5 = pd.read_csv(('R5.csv'))
df_w6 = pd.read_csv(('R6.csv'))
df_w7 = pd.read_csv(('R7.csv'))
df_w8 = pd.read_csv(('R8.csv'))
df_w9 = pd.read_csv(('R9.csv'))
list_dfs = [df_w1, df_w2, df_w3, df_w4, df_w6, df_w7, df_w8, df_w9]


 Specific Thing We Will Do for CSE8B is merge the grades and figure out how many unique grades we have

In [22]:
#We are removing last two empty rows
# df = df.iloc[:-2]
# print("The shape should be (480, 14), shape is: " + str(df.shape))
print("size of grades b00 is: " + str(df_gradesB.shape[0]))
print("size of grades c00 is: " + str(df_gradesC.shape[0]))
print("size of grades A-B is: " + str(df_gradesA_B.shape[0]))
print("size of grades C-D is: " + str(df_gradesC_D.shape[0]))



size of grades b00 is: 147
size of grades c00 is: 259
size of grades A-B is: 147
size of grades C-D is: 258


### <a id='section_general_functions'> General Functions </a> You Can Use Repeatedly / Versatile to Apply to Diff Dataframes 

[- Return](#toc) 
- shorten_english_fluency(input_dataframe) <i> Makes the english choices answers into 1, 2, 3, 4 (in increasing level of english familiarity, respectively) </i>
- describe_col(input_dataframe, input_column) <i> Prints out quick descriptive information about the input column </i> 
- describe_missing(input_dataframe, input_col, n) <i> Prints out example rows with missing columns </i> 
<hr>
- convert_to_quantiative_columns(df_input) <i> finds every column that has the 1 (Not at all ) and 5 ( Completely Choices) and convert them to simple numbers 1 - 5 </i>
- get_names(df_input, word_to_keep) *returns every column name that has the inclusion of the word* 




In [23]:
def get_names(df_input, word_to_keep = '0' ): 
    if word_to_keep == '0': 
        ans = [col for col in df_input.columns]
    else: 
        ans =  [col for col in df_input.columns if word_to_keep in col ]
    print(ans)
    return ans 

In [24]:


def shorten_english_frequency(input_dataframe): 
    """Shortening English Fluency Choices"""
    input_dataframe.loc[(input_dataframe['english_fluency'] ==  'I learned English as a child as my primary language.'), ['english_fluency']]= 4
    input_dataframe.loc[(input_dataframe['english_fluency'] ==  'I learned English as a child in a bilingual or multilingual setting.  I am equally comfortable in English and another language.'), ['english_fluency']]= 3
    input_dataframe.loc[(input_dataframe['english_fluency'] ==  'I learned English after learning another primary language and I am equally comfortable in both languages.'), ['english_fluency']]= 2
    input_dataframe.loc[(input_dataframe['english_fluency'] ==  'I learned English after learning another primary language and I am not as comfortable in English as I am in another language.'), ['english_fluency']]= 1
    
    input_dataframe[["english_fluency"]] = input_dataframe[["english_fluency"]].apply(pd.to_numeric)

    return input_dataframe 

def describe_col(input_dataframe, input_col): 
    """Prints quick descriptive information about the input_col"""
#     o = (input_dataframe[input_col].value_counts(dropna = False, normalize = False, ascending = True ))
    print("There are " + str(input_dataframe[input_col].shape[0]) + " rows in this table")
    print("There are " + str(input_dataframe[input_col].isna().sum()) + " empty values of " + input_col)
    print("Here are all the values (including null values) for the column " + input_col)
    print(input_dataframe[input_col].value_counts(dropna = False))
    print("Here are all the percentages (including null values) for the column  " + input_col)
    print(input_dataframe[input_col].value_counts(dropna = False, normalize = True))
    
    if (input_dataframe[input_col].isna().sum() != 0 ):
        print("Here are the percentages of the values for the column " + input_col)
        print(input_dataframe[input_col].value_counts(normalize = True))

def describe_missing(input_dataframe, input_col, n ): 
    o = (input_dataframe[input_dataframe[input_col].isnull()])
    if (o.shape[0] >= 1): 
        display(o.head(n))
        
        
        


In [25]:
def convert_to_quantiative_columns(df_input):
    """This function will find every column that has the 1 (Not at all ) and 5 ( Completely Choices) and convert them to simple numbers 1 - 5 """
    col_title = [col for col in df_input.columns if 'reflect' in col or 'i_' in col ] 
    #The reason why we are removing 'feel like i don't belong'
    #As well as 'overall_stress' from these edited numbers is because those are 
    #Negative things while the rest of the columns are positive, so we will be replacing those
    #Columns as 1 -> 5, 5 -> 1, and so on.
    col_title = [col for col in col_title if 'do_belong' not in col]
    col_title = [col for col in col_title if 'unstress_level' not in col]
    #These are all the columns whose values we will be changing
#     print(col_title)
    #Looping through every column title and changing response
    for col in col_title: 
        df_input.loc[(df_input[col] == '1 (Not at all)'), [col]]= 1
        df_input.loc[(df_input[col] == '2'), [col]]= 2
        df_input.loc[(df_input[col] == '3'), [col]]= 3
        df_input.loc[(df_input[col] == '4'), [col]]= 4
        df_input.loc[(df_input[col] == '5 (Significantly)'), [col]]= 5
        df_input.loc[(df_input[col] == '5 (Completely)'), [col]]= 5
        
    
    df_input[col_title] = df_input[col_title].apply(pd.to_numeric)

    return df_input
        
    
def convert_to_quantiative_columns_reverse(df_input):
    """This function will take columns and reverse 1 to 5, 2 to 4, 3 to 3 """
    col_title = [col for col in df_input.columns if 'do_belong' in col or 'unstress_level' in col ] 
    #The reason why we are editing the 'do belong' and 'unstress level' 
    #Reversed (1 = 5 and 5 = 1), is because on the survey they were phrased
    #As "put 5 if you feel like you do NOT belong" and put 5 if you feel VERY stressed 
    #So for convenience of data later we've renamed columns and changed them accordingly 
  
    #These are all the columns whose values we will be changing
#     print(col_title)
    
    #Looping through every column title and changing response
    for col in col_title: 
        df_input.loc[(df_input[col] == '1 (Not at all)'), [col]]= 5
        df_input.loc[(df_input[col] == '2'), [col]]= 'dummy_2'
        df_input.loc[(df_input[col] == '4'), [col]]= 2
        df_input.loc[(df_input[col] == 'dummy_2'), [col]]= 4
        df_input.loc[(df_input[col] == '5 (Significantly)'), [col]]= 1
        df_input.loc[(df_input[col] == '5 (Completely)'), [col]]= 1
    
    df_input[col_title] = df_input[col_title].apply(pd.to_numeric)
    return df_input


### <a id='section_2'> Basic General Data Cleaning </a> 

What is happening in this section: 
- Rename Columns of Pre-Survey Data
- Rename Columns of Weekly Classes Survey Questions
- Combine Classes Dataframes into a Combined Dataframe 



In [26]:
#Renaming Column Names for Pre-Survey Data 
df = df.rename(columns={"Timestamp": "time","What.is.your.fluency.with.English.": "english_fluency",'If.your.current.declared.major.'
      + "is.different.from.your.desired.major..i.e..you.hope.to.switch.majors...what.major.do.you.hope.to.switch."
      + "to...Leave.blank.if.this.does.not.apply.to.you..": "switch_major","What.is.your.gender.": "gender",
           "Did.you.enter.UCSD.as.a.transfer.student.from.another..2.year.or.4.year..college.or.university.":"transfer",
             'What.is.the.main.reason.you.are.taking.this.course.':"main_reason",'On.a.scale.of.1.to.5..how.much.'
      + 'experience.did.you.have.with.programming.computer.science.before.you.took.your.FIRST.course.at.UC.San.Diego.':
            'prior_exp','Please.select.all.of.the.CS.programming.experiences.you.had.before.taking.your.FIRST.CS.course.at.UCSD.':
      'cs_exp','Please.rate.your.current.level.of.experience.with.technology.in.general':'tech_exp',
      'On.a.scale.of.1.to.5..how.confident.are.you.about.your.ability.to.do.well.in.this.course.':'confidence_level',
       'What.is.the.MINIMUM.grade.you.think.you.would.be.satisfied.with.in.this.course...' + 
      'If.you.re.taking.this.course.pass.no.pass..note.that.C..is.the.threshold.for.passing...': "min_grade_expected",
      'What.is.your.ethnicity.':'ethnicity','What.is.your.race...Select.all.that.apply.':'race','DeID':'id'})

In [27]:
# rename_columns: renames the google survey questions column names to more manageable column names
def rename_columns(df): 
    df = df.rename(columns={"Timestamp": "time", 'In.the.last.week..approximately.how.many.hours.did.you.spend.' 
        + 'outside.of.class.time.working.on.work.for.this.course.': 'hours_out_of_class',
        'How.challenging.was.the.work.for.this.class.this.week.': 'challenge_level',
        'In.the.past.week..which.of.the.following..if.any..did.you.seek.help.from.work.with.for.this.course.':'resource',
        # 'In.the.past.week..which.of.the.following..if.any..did.you.seek.help.from.work.with.for.this.course.':'help',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.with.' 
        + 'your.ability.to.learn.and.complete.the.work.for.this.course..Requirements.for.other.classes.': 'i_other_classes', 
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.with.'
        + 'your.ability.to.learn.and.complete.the.work.for.this.course..Illness.' : 'i_illness',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Family.obligations.' : 'i_family',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Work.obligations.' : 'i_work',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Social.personal.life.issues.' : 'i_personal',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Confusion.specifically.about.the.assignment.' : 'i_confusion_assignment',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Confusion.generally.about.the.material.' : 'i_confusion_material',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Getting.stuck.on.a.bug.' : 'i_confusion_bug',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Inability.to.get.help.' : 'i_help_inability',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Embarrassment.discomfort.asking.others.for.help.' : 'i_help_discomfort',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Self.doubt.lack.of.confidence.' : 'i_self_doubt',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Embarrassment.discomfort.asking.others.for.help.' : 'i_help_discomfort',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Inability.to.get.help.' : 'i_help_inability',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Lack.of.interest.in.the.assignment.or.material.' : 'i_lack_of_interest',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Inability.to.get.help.' : 'i_help_inability',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Goofing.off.procrastination.' : 'i_procrastination',
        'In.the.past.week..on.a.scale.of.1.to.5..to.what.degree.did.each.of.the.following.interfere.'
        + 'with.your.ability.to.learn.and.complete.the.work.for.this.course..Other..if.applicable..please.specify.below..' : 'i_other',
        'If.you.marked..Other..above..please.specify' : 'n_if_other_custom',
       'What.is.your.current.overall.satisfaction.with.your.performance.in.this.class.' : 'current_satisfaction', 
       'Reflecting.on.your.experiences.over.the.past.week..to.what.extent.do.you.agree.with.the.following.statements..'
        + 'I.feel.accepted.in.this.class..' : 'reflect_accepted',
        'Reflecting.on.your.experiences.over.the.past.week..to.what.extent.do.you.agree.with.the.following.statements..'
        + 'I.feel.comfortable.in.this.class..' : 'reflect_comfortable',
        'Reflecting.on.your.experiences.over.the.past.week..to.what.extent.do.you.agree.with.the.following.statements..'
        + 'I.feel.supported.in.this.class..' : 'reflect_supported',
        'Reflecting.on.your.experiences.over.the.past.week..to.what.extent.do.you.agree.with.the.following.statements..'
        + 'I.feel.like.I.don.t.belong.in.this.class..' : 'reflect_do_belong',
       'At.this.time..approximately.how.many.other.students.in.this.course.would.you.be.'
        + 'comfortable.reaching.out.to.study.with.': 'num_study_students', 
       'Reflecting.on.the.last.week..how.stressed.have.you.been.overall.' :'reflect_unstress_level',
       'Optional..If.you.want..please.enter.any.information.to.expand.on.or.explain.your.answers.to.any.of.the.questions.on.this.survey.' :'optional_expand_answers',
                            
        'Which.CSE.11.section.are.you.enrolled.in.':'cse_11_section', 
        'DeID':'id' })
    return df 
     

In [28]:
#renaming the weekly reflection survey data
dfw1 = rename_columns(df_w1)
dfw2 = rename_columns(df_w2)
dfw3 = rename_columns(df_w3)
dfw4 = rename_columns(df_w4)
dfw5= rename_columns(df_w5)
dfw6 = rename_columns(df_w6)
dfw7 = rename_columns(df_w7)
dfw8 = rename_columns(df_w8)
dfw9 = rename_columns(df_w9)
list_df = [dfw1, dfw2, dfw3, dfw4, dfw5, dfw6, dfw7, dfw8, dfw9] 

In [29]:
def modify_columns(random_dataframe, prefix): 
    """Edits column names by adding prefix to each of them"""
    for col_name in random_dataframe: 
        random_dataframe = random_dataframe.rename(columns={ col_name: prefix + "_" + col_name}) 
    random_dataframe = random_dataframe.rename(columns={ prefix + "_id": "id"}) 
    return random_dataframe

In [30]:
df1 = modify_columns(dfw1, 'wk1')
df2 = modify_columns(dfw2, 'wk2')
df3 = modify_columns(dfw3, 'wk3')
df4 = modify_columns(dfw4, 'wk4')
df5 = modify_columns(dfw5, 'wk5')
df6 = modify_columns(dfw6, 'wk6')
df7 = modify_columns(dfw7, 'wk7')
df8 = modify_columns(dfw8, 'wk8')
df9 = modify_columns(dfw9, 'wk9')

list_df_combo = [df1, df2,df3,df4,df5,df6,df7,df8,df9]
print("the size of the presurvey data is: "+ str(df.shape[0]))
for number, dataframe in enumerate( list_df_combo):
    print("During week " + str(number + 2)  + ", there were " + str(dataframe.shape[0]) +  " students that responded")
    

the size of the presurvey data is: 365
During week 2, there were 375 students that responded
During week 3, there were 363 students that responded
During week 4, there were 308 students that responded
During week 5, there were 390 students that responded
During week 6, there were 357 students that responded
During week 7, there were 385 students that responded
During week 8, there were 369 students that responded
During week 9, there were 389 students that responded
During week 10, there were 372 students that responded


In [31]:

df_og = (df.set_index('id').join(df1.set_index('id') ,how='outer'))
df_og = (df_og ).join(df2.set_index('id') ,how='outer')
df_og = (df_og ).join(df3.set_index('id') ,how='outer')
df_og = (df_og ).join(df4.set_index('id') ,how='outer')
df_og = (df_og ).join(df5.set_index('id') ,how='outer')
df_og = (df_og ).join(df6.set_index('id') ,how='outer')
df_og = (df_og ).join(df7.set_index('id') ,how='outer')
df_og = (df_og ).join(df8.set_index('id') ,how='outer')

# df_presurvey_grades= (df.set_index('id').join(df_grades.set_index('DeID'),how='outer'))

#We're shortening answer length of english fluency (4 = English is primary language, 2 = bilingual, 3 = not primary, etc)
df = shorten_english_frequency(df)
df_og = shorten_english_frequency(df_og)

#Converted all the quantiative cols to numbers
df_og = convert_to_quantiative_columns(df_og)

#Converted all the (columns about Stress Level and Sense of Belonging) quantiative cols to numbers
df_og = convert_to_quantiative_columns_reverse(df_og)

df_og = df_og[~df_og.index.duplicated(keep='last')]
print("The length: " + str(len(df_og.index.unique())) + " should equal the shape: " + str(df_og.shape[0]))

/Users/nayeliguzman/opt/anaconda3/lib/python3.7/site-packages/pandas/core/ops/array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)


The length: 462 should equal the shape: 462


In [32]:
df_og.shape[0]
# display(df)

462

##### Proceeding with df_og, A Note About Missing Survey Data 
<hr> 

- 365 students filled out the pre-survey data in some way (answered at least one question and received an ID) 

After combining all the data, 
- 462 students (unique ids) have filled out some thing at one point, whether it be a weekly reflection or survey data
- 105 of those students did not provide info about their english fluency 

Going forth, we will be <b> dropping the 105 rows </b> with no English fluency information.

<hr> 

After this, we will have 

- 357 rows (student ids) collected overall, of those 462 students
    - 153 students speak english fluently only (43%) 
    - 87 students are bilingual and equally comfortable in English and another language (24.37%)
    - 79 students learned English after learning another primary language and I am equally comfortable in both languages (22%) 
    - 38 are non-native english speakers not as comfortable with English as another language (11%)
    
    
- If we split the grouping of native speakers to be speaking fluently only as well as bilingual, and non-native speakers to be learning english after primary language as well as not as comfortable with English compared to another language, 
    - 240 students we will label as native english speakers (67.22%) 
    - 117 students we will label as non-native english speakers (32.77%) 


<hr>

In [33]:
#By using describe_col function we see there are empty values, will drop those


##----------------------Before dropping
# describe_col(df_og, 'english_fluency')

##----------------------After dropping 
df_og = df_og.dropna(subset=['english_fluency'])
describe_col(df_og, 'english_fluency')


There are 357 rows in this table
There are 0 empty values of english_fluency
Here are all the values (including null values) for the column english_fluency
4.0    153
3.0     87
2.0     79
1.0     38
Name: english_fluency, dtype: int64
Here are all the percentages (including null values) for the column  english_fluency
4.0    0.428571
3.0    0.243697
2.0    0.221289
1.0    0.106443
Name: english_fluency, dtype: float64


In [34]:
#We're creating a column where native english speakers are categorized as having chosen English as primary language
#or bilingual and multilingual setting and equally comfortable in English

df_og.native_bool = 2
df_og.native_bool

df_og['native_bool']  = (df_og['english_fluency'] == 4) 
df_og.loc[(df_og['english_fluency'] == 3), ['native_bool']]= True 
# describe_col(df_og, 'english_fluency')    
# describe_col(df_og, 'native_bool')
df_n = df_og.loc[df_og['native_bool']]
df_nn = df_og.loc[df_og['native_bool'] == False]

# display(df_og)
# df_og.to_csv('file_name.csv', index=False)


##### <a id='section_missing_data'>  Dealing With Missing Data </a> [- Return](#toc) 

Due to people some weeks filling out surveys and other weeks not, we will be using Data Probalistic Imputation for these 
quantitative values 
<br> 
https://afraenkel.github.io/practical-data-science/06/probabilistic-imputation.html 
<br> 
<br>
Essentially to get rid of the empty values of when people did not fill out responses for 1-5 problems, 
we will be drawing distributions from the existing data to fill inside the missing data so our 
mean and variance will be affected as little as possible 

In [35]:
def impute_from_distrib(df_input, col_to_impute):
    '''use probalistic imputation on a column.'''
    #Get the number of empty values we need to replace 
    num_null = df_input[col_to_impute].isnull().sum() # number of nulls
    #Get a distribution with no missing data 
    fill_values = df_input[col_to_impute].dropna().sample(num_null, replace=True)  # draw fill vals from distribution
    fill_values.index = df_input.loc[df_input[col_to_impute].isnull()].index  # align the index, which is missing?
    imputed_df = df_input.fillna({col_to_impute: fill_values.to_dict()})  # fill the vals
    return imputed_df 


def impute_quantitative_cols(inputing_df):
    """This function will take every column that asks 1-5 questions and use the impute from distr function to impute missing data """
    col_titles = [col for col in inputing_df.columns if '_i_' in col or '_reflect' in col 
        or '_current_satisfaction' in col or '_challenge' in col or '_num_study_students' in col]
    for col in col_titles: 
        inputing_df = impute_from_distrib(inputing_df, col)
    return inputing_df


In [36]:
#To keep missing data in df_all 
#we will now start using df_full in the process of filling missing data 
df_full = df_og.copy() 
df_full = impute_quantitative_cols(df_full)

df_full = impute_from_distrib(df_full, 'wk2_hours_out_of_class')


df_full['native_bool']  = (df_full['english_fluency'] == 4) 
df_full.loc[(df_full['english_fluency'] == 3), ['native_bool']]= True 
# describe_col(df_og, 'english_fluency')    
# describe_col(df_og, 'native_bool')


#We can look at the missing percentage of each column 
#And display every column who has at least some missing (null) value in at least one row 
percent_missing = df_full.isnull().sum() * 100 / len(df_full)
missing_value_df_full = pd.DataFrame({'column_name': df_full.columns, 'percent_missing': percent_missing})
still_missing = (missing_value_df_full[missing_value_df_full.percent_missing != 0.000000])
# display(still_missing) 

# df_full.wk2_hours_out_of_class



##### <a id='section_outlier'> How We Handle Outliers </a> [- Return](#toc) 

We will for certain columns such as the hours spent out of class, use our function 
- change outlier(input_df, col, lower_end, higher_end, status) *replaces outliers with median* 

To locate the quantiles (usually .25% and .75%) to locate the outliers of cut off points and replace them with medians. 

In [37]:

def change_outlier(input_df, col, lower_end, higher_end, status, head = 5 ): 
    """identifies every low part, and every high part, and replaces the stuff overlapping with median, returns column """
    Q1 = input_df[col].quantile(lower_end) 
    Q3 = input_df[col].quantile(higher_end) 
    IQR = Q3 - Q1 
    cut_off_max = Q3 + 1.5 * IQR
    cut_off_min = Q1 - 1.5 * IQR
    median = input_df[col].median()
    up_outliers = input_df[(input_df[col] > cut_off_max)]
    low_outliers = input_df[(input_df[col] < cut_off_min)]
    if status != 'replace': 
        print("We would be replacing " + str(up_outliers.shape[0]) + " rows found greater than " 
          + str(cut_off_max) + " with median value of " + str(median))
        
        print("We would be replacing " + str(low_outliers.shape[0]) + " rows found greater than " 
          + str(cut_off_min) + " with median value of " + str(median))
        display(up_outliers[[col]].head(head))
        display(low_outliers[[col]].head(head))
    if status == 'replace': 
        input_df.loc[(input_df[col] > cut_off_max), [col]]= median
        input_df.loc[(input_df[col] < cut_off_max), [col]]= median


#### Concerning How We Handle Outliers of Hours Spent Outside of Course Studying: 

After running descriptive identifying outliers for each column, we have found that usually it seems like hours above 16 hours are unreasonable. As a result, we will be going through the columns and replacing every response that has an answer more than 15 with the median value of that column 

In [38]:
# If you comment out this section, it will print descriptive outlier stats
for col_name in ['wk2_hours_out_of_class', 'wk3_hours_out_of_class', 'wk4_hours_out_of_class',
                 'wk5_hours_out_of_class', 'wk6_hours_out_of_class', 'wk7_hours_out_of_class', 'wk8_hours_out_of_class', 'wk9_hours_out_of_class']:
    change_outlier(df_full, col_name, 0.25, 0.75 , 'check', 1) 

def change_outlier_for_hours(input_df, col): 
    """identifies every low part, and every high part, and replaces the stuff overlapping with median, returns column """
    median = input_df[col].median()
    input_df.loc[(input_df[col] > 15), [col]]= median

for col_name in ['wk2_hours_out_of_class', 'wk3_hours_out_of_class', 'wk4_hours_out_of_class',
                 'wk5_hours_out_of_class', 'wk6_hours_out_of_class', 'wk7_hours_out_of_class', 'wk8_hours_out_of_class', 'wk9_hours_out_of_class']:
    change_outlier_for_hours(df_full, col_name) 


We would be replacing 19 rows found greater than 25.5 with median value of 10.0
We would be replacing 0 rows found greater than -2.5 with median value of 10.0


wk2_hours_out_of_class
id                              
0EV6RTFG                    27.0

Empty DataFrame
Columns: [wk2_hours_out_of_class]
Index: []

We would be replacing 12 rows found greater than 21.0 with median value of 9.0
We would be replacing 0 rows found greater than -3.0 with median value of 9.0


wk3_hours_out_of_class
id                              
23RJJJAB                    40.0

Empty DataFrame
Columns: [wk3_hours_out_of_class]
Index: []

We would be replacing 5 rows found greater than 31.75 with median value of 12.0
We would be replacing 0 rows found greater than -6.25 with median value of 12.0


wk4_hours_out_of_class
id                              
701C32D7                    40.0

Empty DataFrame
Columns: [wk4_hours_out_of_class]
Index: []

We would be replacing 12 rows found greater than 27.0 with median value of 10.0
We would be replacing 0 rows found greater than -5.0 with median value of 10.0


wk5_hours_out_of_class
id                              
23RJJJAB                    40.0

Empty DataFrame
Columns: [wk5_hours_out_of_class]
Index: []

We would be replacing 16 rows found greater than 25.5 with median value of 10.0
We would be replacing 0 rows found greater than -2.5 with median value of 10.0


wk6_hours_out_of_class
id                              
112Y19QQ                    35.0

Empty DataFrame
Columns: [wk6_hours_out_of_class]
Index: []

We would be replacing 20 rows found greater than 28.0 with median value of 12.0
We would be replacing 0 rows found greater than -4.0 with median value of 12.0


wk7_hours_out_of_class
id                              
23RJJJAB                    40.0

Empty DataFrame
Columns: [wk7_hours_out_of_class]
Index: []

We would be replacing 17 rows found greater than 25.5 with median value of 10.0
We would be replacing 0 rows found greater than -2.5 with median value of 10.0


wk8_hours_out_of_class
id                              
23RJJJAB                    30.0

Empty DataFrame
Columns: [wk8_hours_out_of_class]
Index: []

KeyError: 'wk9_hours_out_of_class'

In [ ]:
df_native = df_full.loc[df_full['native_bool']]
df_non_native = df_full.loc[df_full['native_bool'] == False]

### <a id='section_dfs'> List of Main Dataframes </a> 

---
[- Return](#toc) 

These will be the dataframes we are calling
- df = Pre-survey data
- df_og = Pre-survey data combined with responses from weeks 2-9, leaving all missing data as well as outliers
- df_full = Pre-survey data combined with respones from 2-9, with data imputed as well as outliers replaced with medians 
- df_presurvey_grades = Combination of Pre-survey data and grades data 
- df_n = part of df_og that only contains responses from native english speakers 
- df_nn = part of df_og that only contains responses from non-native english speakers
- df_native = part of df_full that only contains responses from native english speakers, imputed data 
- df_non_native = part of df_full that only contains responses from non-native english speakers, imputed data




### <a id='section_funcs_mean'> General Mean Functions </a> [- Return](#toc) 
These will be usable functions for getting means of columns and editing them
- get_single_mean(df_input, col) <i> Gets mean values for just one specific column </i> 
- get_mean(df_input, col_list) *returns mean of every single column name in the column list parameter*




In [ ]:
def get_single_mean(df_input, col):
    '''get and return the mean values for this column.'''
    #to numeric converts strings to integer values, coerce replaces non-numeric with nan
    mean = pd.to_numeric(df_input[col], errors='coerce').mean()
    print("The mean for " + col + " is " + str(mean))
    return mean 

def get_mean(df_input, col_list):
    '''get and return the mean values for this column.'''
    answers = []
    #to numeric converts strings to integer values, coerce replaces non-numeric with nan
    for col in col_list: 
        mean = pd.to_numeric(df_input[col], errors='coerce').mean()
#         print("The mean for " + col + " is " + str(mean))
        answers.append(mean)
    return answers 


# General Get Dataframe Functions

In [ ]:
def get_df_n(df, print_status = False ): 
  new_dataframe = df[df['native_bool'] == True]
  if print_status:
    print(str(new_dataframe.shape[0]) + " native students")
  return new_dataframe

def get_df_nn(df, print_status = False ): 
  new_dataframe = df[df['native_bool'] == False]
  if print_status:
    print(str(new_dataframe.shape[0]) + " non-native students")
  return new_dataframe

def get_df_male(df, print_status = False ): 
  new_dataframe = df[df['gender'] == 'Male']
  if print_status:
    print(str(new_dataframe.shape[0]) + " male students")
  return new_dataframe

def get_df_female(df, print_status = False ): 
  new_dataframe = df[df['gender'] == 'Female']
  if print_status:
    print(str(new_dataframe.shape[0]) + " female students")
  return new_dataframe

def get_df_n_female(df, print_status = False ): 
  new_dataframe = df[(df['native_bool'] == True) & (df['gender'] == 'Female')]
  if print_status:
    print(str(new_dataframe.shape[0]) + " native female students")
  return new_dataframe
  
def get_df_n_male(df, print_status = False ): 
  new_dataframe = df[(df['native_bool'] == True) & (df['gender'] == 'Male')]
  if print_status:
    print(str(new_dataframe.shape[0]) + " native male students")
  return new_dataframe

def get_df_nn_female(df, print_status = False ): 
  new_dataframe = df[(df['native_bool'] == False) & (df['gender'] == 'Female')]
  if print_status:
    print(str(new_dataframe.shape[0]) + " non-native female students")
  return new_dataframe

def get_df_nn_male(df, print_status = False ): 
  new_dataframe = df[(df['native_bool'] == False) & (df['gender'] == 'Male')]
  if print_status:
    print(str(new_dataframe.shape[0]) + " non-native male students")
  return new_dataframe
  

# General Statistical Test Functions

These will be usable functions for statistical testing

- run_t_test(list_from_sample_1, list_from_sample_2, alpha) Runs a two-sided test for the null hypothesis that 2 independent samples have identical average (expected) values. This test assumes that the populations have identical variances by default.
- run_welch_test(list_from_sample_1, list_from_sample_2, equal_var = False, describe = True) Runs a two-sided test for the null hypothesis that 2 independent samples have identical average (expected) values. This test DOES NOT assume that the populations have identical variances by default.

In [ ]:
from scipy.stats import sem
from scipy.stats import t
 
# function for calculating the t-test for two independent samples
def independent_ttest(data1, data2):
	# calculate means
	mean1, mean2 = np.mean(data1), np.mean(data2)
	# calculate standard errors
	se1, se2 = sem(data1), sem(data2)
	# standard error on the difference between the samples
	sed = math.sqrt(se1**2.0 + se2**2.0)
	# calculate the t statistic
	t_stat = (mean1 - mean2) / sed
	# degrees of freedom
	df = len(data1) + len(data2) - 2
	# calculate the p-value
	p = (1.0 - t.cdf(abs(t_stat), df)) * 2.0
	# return everything
	return t_stat, df, p

def run_t_test(one, two ):
  # calculate the t test
	
  t_stat, df, p = independent_ttest(one, two )
	
  print('T-test=%.3f, df=%d, p=%.3f' % (t_stat, df, p))
  # interpret via p-value
  if p > 0.05:
    print('Decision: Fail to Reject the null hypothesis')
  else:
    print('Decision: Reject the null hypothesis')


In [ ]:
#Welch's t-test
def run_welch_test(a,b, equal_var=False,describe = True ):
    #Calculate degrees of freedom
    dof_num = (a.var()/a.size + b.var()/b.size)**2
    dof_den =(a.var()/a.size)**2 / (a.size-1) + (b.var()/b.size)**2 / (b.size-1)
    dof = dof_num/dof_den
    #Perform Welch's t-test
    test, p_val = ttest_ind(a,b, equal_var = equal_var)
    if describe:
        print(f"Welch's t-test={test}, df={dof}, p-value={p_val}")
        #Print decision.
        if p_val<0.05:
            print('Decision: Reject the null hypothesis')
        else:
            print('Decision: Fail to reject the null hypothesis')
    return ttest_ind(a,b, equal_var = False)



In [ ]:

from scipy.stats import mannwhitneyu
import statistics 

#Mann-Whitney U test
def run_Mann_Whitney_test(NNES, NES):
    #Calculate the median
    NNES_mdn = statistics.median(NNES)
    NES_mdn = statistics.median(NES)
    print('NNES median: ' + str(NNES_mdn))
    print('NES median: ' + str(NES_mdn))
 
    #Perform Mann Whitney U Test
    u_statistic, p_val = mannwhitneyu(NNES, NES,use_continuity = True)
    print(f"Mann Whitney U-test={u_statistic}, p-value={p_val}")
      #Print decision
    if p_val<0.05:
        print('Decision: Reject the null hypothesis')
    else:
        print('Decision: Fail to reject the null hypothesis')
    return mannwhitneyu(NNES, NES, use_continuity = True)


In [ ]:

from scipy.stats import levene

def run_Levene_test(df1, df2):
    stat, p = levene(df1, df2, center="mean")
    if (p < 0.05) == True:
      print('Reject the null hypothesis that the variances are equal.')
      print("the p value is: " + str(p) + " < 0.05")
      print("A significant result indicates that the variances are not equal and would ")
      print("be a violation of the assumption of equal variances.")

    else:
      print('Cannot reject the null hypothesis that the variances are equal.')
      print("The null hypothesis: the variances across both nn and ne groups are equal for confidence level")
      print("the p value is: " + str(p) + " > 0.05")
      print("If this test was for ANCOVA, you may proceed to check other assumptions.")

    print(dfa_nn['confidence_level'].var())
    dfa_ne['confidence_level'].var()
    return


# Research Question Hours



## Q: Is there a difference in the amount of time spent outside of class (for readings, assignments etc) in a CS course between native and non-native English speakers?

In [ ]:
def impute_hours(inputing_df):
    col_titles = [col for col in inputing_df.columns if 'hours_out_of_class' in col]
    for col in col_titles: 
        inputing_df = impute_from_distrib(inputing_df, col)
    return inputing_df


def change_outlier_for_hours(input_df, col): 
    """identifies every low part, and every high part, and replaces the stuff overlapping with median, returns column """
    median = input_df[col].median()
    input_df.loc[(input_df[col] > 20), [col]]= median
    return input_df

hours_list = get_names(df_full, 'hours_out_of_class')
df_hours_without_outliers = df_full.copy()

for col_name in ['wk2_hours_out_of_class', 'wk3_hours_out_of_class', 'wk4_hours_out_of_class',
                 'wk5_hours_out_of_class', 'wk6_hours_out_of_class', 'wk7_hours_out_of_class', 'wk8_hours_out_of_class', 'wk9_hours_out_of_class']:
    df_hours_without_outliers = change_outlier_for_hours(df_hours_without_outliers, col_name) 


df_hr = df_hours_without_outliers.copy()
df_hours_without_outliers = df_hours_without_outliers[['english_fluency', 'native_bool', 'wk2_hours_out_of_class',
                    'wk3_hours_out_of_class', 'wk4_hours_out_of_class', 'wk5_hours_out_of_class',
                    'wk6_hours_out_of_class', 'wk7_hours_out_of_class', 'wk8_hours_out_of_class', 'wk9_hours_out_of_class']]

#comment and uncomment this to impute or not impute the data
df_hours_without_outliers = impute_hours(df_hours_without_outliers)
df_hours = df_hours_without_outliers.copy()

# describe_col(df_hours_without_outliers_imputed, 'wk3_hours_out_of_class')

df_hours_n = df_hours[df_hours['native_bool'] == True ]
df_hours_nn = df_hours[df_hours['native_bool'] == False ]
overall_list_hours_n = []
overall_list_hours_nn = []

for col in hours_list: 
    overall_list_hours_n.append(df_hours_n[col].tolist())

for col in hours_list: 
    overall_list_hours_nn.append(df_hours_nn[col].tolist())

overall_list_hours_n = [y for x in overall_list_hours_n for y in x]
overall_list_hours_nn = [y for x in overall_list_hours_nn for y in x]


print("For " + str(len(overall_list_hours_n)) + " inputs from native english speaking students, "
  + "their mean hours studied was " +  str(np.mean(overall_list_hours_n)))
print("For " + str(len(overall_list_hours_nn)) + " inputs from non-native english speaking students, "
  + "their mean hours studied was " +  str(np.mean(overall_list_hours_nn)))

# print("--------------------")
print(ttest_ind(overall_list_hours_n,overall_list_hours_nn, nan_policy = 'omit'))
print(ttest_ind(overall_list_hours_n,overall_list_hours_nn,  equal_var = False, nan_policy = 'omit'))

print("--------------------")
# run_t_test(overall_list_hours_n, overall_list_hours_nn)
# run_welch_test(overall_list_hours_n, overall_list_hours_nn)


In [ ]:
def make_simple_mean_df(df, col_input = 'wk2_hours_out_of_class', group_input = 'native_bool' ):
    df_just_other_classes = df[[col_input, group_input]]
    new_name = "avg_of_" + col_input
    df_just_other_classes = df_just_other_classes.rename(columns={group_input: "native_bool", col_input: new_name})
    df_just_other_classes = df_just_other_classes.reset_index(drop=True)
    means_table = df_just_other_classes.groupby('native_bool').mean()
    display(means_table)
    
    var_table = df_just_other_classes.groupby('native_bool').var()
    display(var_table)
    return means_table


#### Null Hypothesis:
The average hours of class spent outside studying for non-native english speakers is equal to the average hours of class spent outside studying for native english speakers.
#### Alternative Hypothesis: 
The average hours are different

#### Type of Statistical Analysis: 
##### Independent Samples T Test

- Assumption of Independence: you need two independent, categorical groups that represent your independent variable. Yes
- Assumption of normality: the dependent variable should be approximately normally distributed. The dependent variable should also be measured on a continuous scale.
- Assumption of Homogeneity of Variance: The variances of the dependent variable should be equal.

### <a id='section_RQ1_graphs'> Research Question Graphs #1 </a>   [- Return](#toc) 


In [ ]:
#Checking Normality of dependent variable (hours out of class spent studying for class)
from matplotlib import pyplot
pyplot.hist(overall_list_hours_n)
pyplot.hist(overall_list_hours_nn)


In [ ]:
df_hours_all = df_hours
keys = [c for c in df_hours_all if c.startswith('wk')]
df_hours_all = pd.melt(df_hours_all, id_vars='native_bool', value_vars=keys, value_name='hours')
df_hours_all.loc[(df_hours_all['variable'] == 'wk2_hours_out_of_class' ), ['variable']]= 2
df_hours_all.loc[(df_hours_all['variable'] == 'wk3_hours_out_of_class' ), ['variable']]= 3
df_hours_all.loc[(df_hours_all['variable'] == 'wk4_hours_out_of_class' ), ['variable']]= 4
df_hours_all.loc[(df_hours_all['variable'] == 'wk5_hours_out_of_class' ), ['variable']]= 5
df_hours_all.loc[(df_hours_all['variable'] == 'wk6_hours_out_of_class' ), ['variable']]= 6
df_hours_all.loc[(df_hours_all['variable'] == 'wk7_hours_out_of_class' ), ['variable']]= 7
df_hours_all.loc[(df_hours_all['variable'] == 'wk8_hours_out_of_class' ), ['variable']]= 8
df_hours_all.loc[(df_hours_all['variable'] == 'wk9_hours_out_of_class' ), ['variable']]= 9
df_hours_all = df_hours_all.rename(columns={"variable": "week"})
df_hours_all.columns

graph_1hour = sns.catplot(x="native_bool", y="hours", hue = 'week', kind="point", data= df_hours_all);
graph_1hour.set(ylim=(0, None))
print(graph_1hour)

sns.catplot(x= 'week', y="hours", hue="native_bool", kind="box", data= df_hours_all);
# sns.catplot(x="week", y="hours", hue="native_bool",kind="violin", data= df_hours_all);

In [ ]:
# df_hours_n.wk2_hours_out_of_class 

In [ ]:
for col in hours_list:
    col_test = col
    print("Independent T-Test for Column " + col + " is " + str(ttest_ind(df_hours_n[col_test], df_hours_nn[col_test], equal_var=False)[1]))


In [ ]:
ttest_ind(overall_list_hours_nn, overall_list_hours_n, equal_var=False)

### <a id='section_RQ1_conclusion'> Research Question Conclusion #1 </a>   [- Return](#toc) 
##### Is there a difference in the amount of time spent outside of class (for readings, assignments etc) in a CS course between native and non-native English speakers?

Technical Notes:
- used ttest_ind underestimates p for unequal variances
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html
- histogram does not show very normal distribution? 

We ran a T-test using for the means of two independent samples of scores and with a p value of 4.03e-07, we *reject* the null hypothesis in that overall there 




## A: Yes, the average hours spent studying for non-native speakers are statistically higher than native english speakers. 


Statistically different: Native students spend about 5.5 hrs on average, non-native about 6.1 hrs on average across all 9 weeks of CSE 11

# <a id='section_RQG'> Research Question Grades </a> 
  [- Return](#toc) 


### Q: Is there a difference in the overall grade received by non-native english speaker students and native english speaker students? 

In [ ]:
df_grades = pd.read_csv(os.path.join('/content/drive/Shared drives/CERSummerResearch/data/DeID GradeReporting_CSE11_F19.csv'))
print(str(df_grades.shape[0]) + " students received grades in the class.")
print(str((df_full.shape[0]/df_grades.shape[0])*100) + " % of students filled out the pre-survey.")

In [ ]:
df_grades_mini = df_grades[['Overall.weighted.course.percentage', 'Final.exam.percentage', 'DeID']]
dfg = (df.set_index('id')).join(df_grades_mini.set_index('DeID'))
dfg = dfg.rename(columns={"Overall.weighted.course.percentage": "overall_grades", "Final.exam.percentage": "final_exam"})
dfg['native_bool']  = (dfg['english_fluency'] == 4) 
dfg.loc[(dfg['english_fluency'] == 3), ['native_bool']]= True 
dfg.columns

#### <a id='section_RQG_graphs'> Research Question Graphs On Overall Grades </a>

   [- Return](#toc) 


In [ ]:
graph_1 = sns.catplot(x="native_bool", y="overall_grades", kind="box", data=dfg, );
graph_1.set(ylim=(0, None))
print(graph_1)
graph_2 = sns.catplot(x="native_bool", y="overall_grades", hue = "confidence_level", kind="box", data=dfg);
graph_2.set(ylim=(0, None))
print(graph_2)

In [ ]:
# graph_2 = sns.distplot(x="native_bool", y="overall_grades", hue = "confidence_level", kind="box", data=dfg);
# 


In [ ]:
dfg_imputed = impute_from_distrib(dfg, 'overall_grades')
dfg_n = dfg[dfg['native_bool'] == True]
dfg_nn = dfg[dfg['native_bool'] == False]

dfg_imputed_n = dfg_imputed[dfg_imputed['native_bool'] == True]
dfg_imputed_nn = dfg_imputed[dfg_imputed['native_bool'] == False]


get_single_mean(dfg_n, 'overall_grades')
get_single_mean(dfg_nn, 'overall_grades')
print("The variance for native speaker overall grade score is " + str(np.var(dfg_n.overall_grades)))
print("The variance for non-native speaker overall grade score is " + str(np.var(dfg_nn.overall_grades)))
ttest_ind(dfg_n['overall_grades'], dfg_nn['overall_grades'], equal_var=False)
print(ttest_ind(dfg_n['overall_grades'], dfg_nn['overall_grades'], equal_var=False, nan_policy = 'omit'))

print("")
print("-------------RESULTS WITH IMPUTED DATA-----------------")
print("")
get_single_mean(dfg_imputed_n, 'overall_grades')
get_single_mean(dfg_imputed_nn, 'overall_grades')
print("The variance for native speaker overall grade score is " + str(np.var(dfg_imputed_n.overall_grades)))
print("The variance for non-native speaker overall grade score is " + str(np.var(dfg_imputed_nn.overall_grades)))
print(ttest_ind(dfg_imputed_n['overall_grades'], dfg_imputed_nn['overall_grades'], equal_var=False))
print(ttest_ind(dfg_imputed_n['overall_grades'], dfg_imputed_nn['overall_grades'], equal_var=False, nan_policy = 'omit'))




In [ ]:
import seaborn as sns
# Method 1: on the same Axis
a = sns.distplot( dfg_n.overall_grades , bins = 50,  color="skyblue", label="Native English Speakers", )
a = sns.distplot( dfg_nn.overall_grades , bins = 50, color="red", label="Non-Native English Speakers")
a.set_title('Distribution of Overall Grades For Native VS Non-Native English Speakers')
a.set_ylabel('Number of Students')
a.set_xlabel('Overall Grade (%)')
plt.legend()


In [ ]:
print("Mean for I learned English as a child as my primary language overall grade is " + str(dfg[dfg['english_fluency'] == 4 ].overall_grades.mean()))
print("Mean for bilingual or multilingual setting.  I am equally comfortable in English and another language. overall grade is " + str(dfg[dfg['english_fluency'] == 3 ].overall_grades.mean()))
print("Mean another primary language and I am equally comfortable in both languages average overall grade is " + str(dfg[dfg['english_fluency'] == 2 ].overall_grades.mean()))
print("Mean another primary language and I am not as comfortable in English as I am in another language. overall grade is " + str(dfg[dfg['english_fluency'] == 1 ].overall_grades.mean()))

dfg.corr(method ='pearson') 

    



In [ ]:
# #Welch's t-test
# def welch_t(a,b, equal_var=False,describe = True ):
#     #Calculate degrees of freedom
#     dof_num = (a.var()/a.size + b.var()/b.size)**2
#     dof_den =(a.var()/a.size)**2 / (a.size-1) + (b.var()/b.size)**2 / (b.size-1)
#     dof = dof_num/dof_den
#     #Perform Welch's t-test
#     test, p_val = ttest_ind(a,b, equal_var = equal_var)
#     if describe:
#         print(f"Welch's t-test = {test}\np-value: {p_val}\nDoF: {dof}")
#         #Print decision.
#         if p_val<0.05:
#             print('Decision: Reject the null hypothesis')
#         else:
#             print('Decision: Fail to reject the null hypothesis')
#     return ttest_ind(a,b, equal_var = False)

welch1 = run_welch_test(dfg_imputed_n.overall_grades, dfg_imputed_nn.overall_grades)


## A: Yes, non-native students perform significantly higher than native students
[- Return](#toc) 

After running the t-test and getting a p-value less than 0.05, we reject the null hypothesis of identical average scores of non-native english speaker students and native english speaker students 

# Research Question Confidence Level

### Q: Are the starting confidence level of native english speakers statistically different from non-native english speakers?

In [ ]:
dfr = df_og.copy() 
# dfr = dfr[dfr['prior_exp'] == 3
dfr['native_bool']  = (dfr['english_fluency'] == 4) 
dfr.loc[(dfr['english_fluency'] == 3), ['native_bool']]= True 
y = 'confidence_level'

# get_names(df_w9)
# dfr = convert_wk9_col_to_quantitative(dfr, [y])

#Comment and Uncomment to see differences if rather than dropping na, you imputed data
# dfr = impute_from_distrib(dfr, y)
print("Originally, there are " + str(dfr[y].isna().sum()) + " empty values for " + y + " overall") 
dfr=dfr.dropna(subset=[y])

print("Dropping empty falues, there are now " + str(dfr[y].isna().sum()) + " empty values for " + y + " overall") 
print("Printing out means for " + y) 
print(" average " + y + " " + str(round(get_single_mean(get_df_n(dfr, True), y), 4)) + "") 
print(" average " + y + " " + str(round(get_single_mean(get_df_nn(dfr, True), y), 4))+ "") 
# print(" average " + y + " " + str(round(get_single_mean(get_df_n_female(dfr, True), y), 4))+ "") 
# print(" average " + y + " " + str(round(get_single_mean(get_df_nn_female(dfr, True), y), 4))+ "") 
# print(" average " + y + " " + str(round(get_single_mean(get_df_n_male(dfr, True), y), 4))+ "") 
# print(" average " + y + " " + str(round(get_single_mean(get_df_nn_male(dfr, True), y), 4))+ "") 
# print(" average " + y + " " + str(round(get_single_mean(get_df_female(dfr, True), y), 4))+ "") 
# print(" average " + y + " " + str(round(get_single_mean(get_df_male(dfr, True), y), 4))+ "") 
import scipy.stats as st

dfr_n = get_df_n(dfr)
dfr_nn = get_df_nn(dfr)
# dfr_f = get_df_female(dfr)
# dfr_m = get_df_male(dfr)
# dfr_n_female = get_df_n_female(dfr)
# dfr_n_male = get_df_n_male(dfr)
# dfr_nn_female = get_df_nn_female(dfr)
# dfr_nn_male = get_df_nn_male(dfr)
 
# data_dfr = {'Native':[get_single_mean(dfr_n, y),get_single_mean(dfr_n_male, y),get_single_mean(dfr_n_female, y),], 
#         'Non-Native':[get_single_mean(dfr_nn, y),get_single_mean(dfr_nn_male, y),get_single_mean(dfr_nn_female, y),],
#         'N & Non-N':[get_single_mean(dfr, y),get_single_mean(dfr_m, y),get_single_mean(dfr_f, y),],
#         'Type':['Male & Female', 'Male', 'Female']
#         } 
# dfr_special = pd.DataFrame(data_dfr).set_index('Type')
# display(dfr_special)

print(st.levene( dfr_n[y], dfr_nn[y]))
print("P value greater than 0.05, can run T-Test")
# print("P value less than 0.05, run Welch Test equal_var = False")

# print("")
# print("-----T-Test For Native & Non-Native---------------------")
# run_t_test(dfr_n[y], dfr_nn[y])
# print("")
# print("--------T-Test For Male & Female ---------------------")
# run_t_test(dfr_m[y], dfr_f[y])
# print("")
# print("-----T-Test For Native Male & Native Female---------------------")
# run_t_test(dfr_n_male[y], dfr_n_female[y])
# print("")
# print("-----T-Test For Non-Native Male & Non-Native Female---------------------")
# run_t_test(dfr_nn_male[y], dfr_nn_female[y])
# print("")
# print("-----T-Test For Native Male & Non-Native Male---------------------")
# run_t_test(dfr_n_male[y], dfr_nn_male[y])
# print("")
# print("-----T-Test For Native Female & Non-Native Female---------------------")
# run_t_test(dfr_n_female[y], dfr_nn_female[y])


The results to not change for imputed vs non imputed data.
There are 6 empty rows for confidence level so we will impute these rows when running analysis.
Then we will drop these rows to check if the result is the same with non-imputed data.

In [ ]:
df['native_bool']  = (df['english_fluency'] == 4) 
df.loc[(df['english_fluency'] == 3), ['native_bool']]= True 
dfc = df.copy()
dfc_full = dfc.copy()     

#-----------Check if result changes with imputation
dfc_full = impute_from_distrib(dfc_full, 'confidence_level')
describe_col(dfc_full,'confidence_level')


# #-----------Check if result changes with dropping empty rows
# dfc_full = dfc_full.dropna(subset=['confidence_level'])
# describe_col(dfc_full,'confidence_level')

#getting the population size of native and non native English speakers
dfc_n = dfc_full[dfc_full['native_bool'] == True]
dfc_nn = dfc_full[dfc_full['native_bool'] == False]
print("The population size of NES is " + str(dfc_n.shape[0]))
print("The population size of NNES is " + str(dfc_nn.shape[0]))

#getting the mean confidence 
mean_confidence_native = get_single_mean(dfc_full[dfc_full['native_bool'] == True], 'confidence_level')
mean_confidence_non_native = get_single_mean(dfc_full[dfc_full['native_bool'] == False], 'confidence_level')
print("The mean confidence level for native english speakers is " + str(mean_confidence_native))
print("The mean confidence level for non-native english speakers is " + str(mean_confidence_non_native))

#printing the tests
print("---------------------T-Test---------------------")
run_t_test(dfc_full[dfc_full['native_bool'] == True].confidence_level, dfc_full[dfc_full['native_bool'] == False].confidence_level)
print("---------------------Welch Test-------------------")
run_welch_test(dfc_full[dfc_full['native_bool'] == True].confidence_level, dfc_full[dfc_full['native_bool'] == False].confidence_level)
print('----------------Mann-Whitney U test---------------')
run_Mann_Whitney_test(dfc_full[dfc_full['native_bool'] == True].confidence_level,dfc_full[dfc_full['native_bool'] == False].confidence_level)


Regardless of imputation the results of these tests do not change

In [ ]:
#double checking the t-test!
df_new = dfc_full.copy()
df_confidence_n = df_new [df_new ['native_bool'] == True ]
df_confidence_nn = df_new [df_new ['native_bool'] == False ]

result = ttest_ind(df_confidence_n['confidence_level'],df_confidence_nn['confidence_level'],equal_var=False)
                
if (result.pvalue < 0.05):
  print("Reject the null hypothesis that the means of " + y + " are equal for native and non-native.")
  print(str(result.pvalue) + "< 0.05")
  print('T-test results for average ' + y + ' between native and non-native:')
  print(str(result))
else:
  print("We cannot reject the null hypotheis that the means for " + y + " are equal for native and non-native")
  print(str(result.pvalue) + '> 0.05')
  print('T-test results for average ' + y + ' between native and non-native:')
  print(str(result))


In [ ]:

dfgc = dfc_full.copy(deep = True) 

df_confidence_n = dfgc[dfgc['native_bool'] == True ]

df_confidence_nn = dfgc[dfgc['native_bool'] == False ]

In [ ]:
df_confidence = dfgc[['native_bool', 'confidence_level']]
print("Values for native english speakers")
print(df_confidence_n['confidence_level'].value_counts(normalize = True ).sort_index())
print("Values for non-native english speakers")
print(df_confidence_nn['confidence_level'].value_counts(normalize = True ).sort_index())

In [ ]:
confidence_data = {'1 (Not at all confident)':[0.020649, 0.028369], '2 ':[0.020649,0.049645], 
        '3':[0.247788, 0.319149], '4':[0.466077,0.397163],
        '5 Extremely confident': [0.244838, 0.205674]} 

df_confidence_percentage = pd.DataFrame(confidence_data , index = ["Native", "Non-Native"])
df_confidence_percentage.plot.barh(stacked=True, colormap='RdYlGn').legend(bbox_to_anchor=(1, 0.5))
plt.title('Confidence Interval ')
plt.xlabel('Percentage of Confidence Interval')
plt.ylabel('Type of English Speaker')

### Color Maps
[Colors](https://matplotlib.org/tutorials/colors/colormaps.html)


In [ ]:
print("The Average Native English Speaker Confidence Level is: " + str(np.mean(df_confidence_n.confidence_level)))
print("the stdv of native English Speakers Confidenec Level is: " + str(df_confidence_n.confidence_level.std()))
      
print("The Average Non-Native English Speaker Confidence Level is: " + str(np.mean(df_confidence_nn.confidence_level)))
print("the stdv of Non-Native English Speakers Confidenec Level is: " + str(df_confidence_nn.confidence_level.std()))

print("Running Tests to see if they are significantly different")
# run_welch_test(df_confidence_n.overall_grades, df_confidence_nn.overall_grades)
# run_t_test(df_confidence_n.overall_grades, df_confidence_nn.overall_grades)

In [ ]:
# df['native_bool']  = (df['english_fluency'] == 4) 
# df.loc[(df['english_fluency'] == 3), ['native_bool']]= True 
# dfc = df.copy()
# dfc_full = dfc.copy()     

# # dfc_full = impute_from_distrib(dfc_full, 'confidence_level')
# describe_col(dfc_full, 'confidence_level')

# mean_confidence_native = get_single_mean(dfc_full[dfc_full['native_bool'] == True], 'confidence_level')
# mean_confidence_non_native = get_single_mean(dfc_full[dfc_full['native_bool'] == False], 'confidence_level')

# print("The mean confidence level for native english speakers is " + str(mean_confidence_native))
# print("The mean confidence level for non-native english speakers is " + str(mean_confidence_non_native))

# print("---------------------T-Test---------------------")
# run_t_test(dfc_full[dfc_full['native_bool'] == True].confidence_level, dfc_full[dfc_full['native_bool'] == False].confidence_level)
# print("---------------------Welch Test-------------------")
# run_welch_test(dfc_full[dfc_full['native_bool'] == True].confidence_level, dfc_full[dfc_full['native_bool'] == False].confidence_level)




### A: No, the non-native english speakers do not have a statistically significant lower overall confidence level 

### ANCOVA. Do non-native English speakers have a statistically significant lower overall confidence level after controlling for gender and prior experience?

It was shown that prior experience and gender were strongly correlated with confidence level. We will use ANCOVA to determine whether the lower overall confidence level of non-native English speakers is still statistically significant by controlling for gender and prior experience. 

For this analysis: gender and prior experience are the covariates, language fluency is the independent variable, and confidence level is the dependent variable. 

Assumptions for ANCOVA:
 http://web.mnstate.edu/malonech/Psy633/Notes/Mertler%20&%20Vannatta%20Ch.%205%20ANCOVA.pdf
 
http://oak.ucc.nau.edu/rh232/courses/eps625/handouts/ancova/understanding%20ancova.pdf
 1.) normality of data (dependent variable - confidence level) for any level of the independent variable. Will be assessed by visual inspection and q-q plots.
2.)Assumption of equal variances. To test if the overall confidence levels of each group is equal we will use the Levene Test. 
3.) Assumption that the relationship between the covariate and dependent variable is linear. To test this assumption we will use the ordinary least squares function.  
4.) Assumption of Homogeneity of Regression slopes will be tested by checking that the means of the covariates is equal across both factors (indpendent variable). 

In [ ]:

dfa = dfc_full.copy(deep = True)
dfa = dfa.dropna(subset=['native_bool'])

# ##check for empty values of native bool and confidence level
# #describe_col(dfa,'native_bool')
# #describe_col(dfa,'confidence_level')

#-----------Check if result changes with imputation
dfa = impute_from_distrib(dfa, 'confidence_level')
#describe_col(dfa,'confidence_level')

# ##-----------Check if result changes with dropping empty rows
# # dfa = dfa.dropna(subset=['confidence_level'])
# # describe_col(dfa,'confidence_level')

df_d = df_d.rename(columns = {"Gender (Binary)":'gender'})
dfa = (dfa.set_index('id').join(df_d.set_index('DeID') ,how='left'))

#coding the native_bool column Native = 1, Non-Native = 0
dfa['native_bool_num'] = ''
dfa.loc[(dfa['native_bool'] == True ), ['native_bool_num']]= 1
dfa.loc[(dfa['native_bool'] == False ), ['native_bool_num']]= 0
dfa[['native_bool_num']] = dfa[['native_bool_num']].apply(pd.to_numeric)

#coding the gender column male - 3, female - 2, non-binary - 1
dfa=dfa.dropna(subset=['gender']) #drop empty
dfa['gender_num'] = 0
dfa.loc[(dfa['gender'] == 'M' ), ['gender_num']]= 3
dfa.loc[(dfa['gender'] == 'F' ), ['gender_num']]= 2
dfa.loc[(dfa['gender'] == 'Non-Binary' ), ['gender_num']]= 1
dfa[['gender']] = dfa[['gender_num']].apply(pd.to_numeric)
print("total Students is " + str(dfa.shape[0]))

# describe_col(dfa,'gender_num')
##----------un-comment this section to check results using imputation-----------
dfa = impute_from_distrib(dfa,'gender_num')
dfa = impute_from_distrib(dfa,'prior_exp')

# ##----------un-comment this section to check results by dropping rows with empty values
# dfa=dfa.dropna(subset=['confidence_level'])

##separate dataframes for independent variable 
dfa_nn = dfa[dfa['native_bool_num'] == 0 ]
dfa_ne = dfa[dfa['native_bool_num'] == 1 ]
print("total NN Students is " + str(dfa_nn.shape[0]))
print("total NE Students is " + str(dfa_ne.shape[0]))

# describe_col(dfa,'gender_num')
# display(dfa)
#print out the data types
# print(dfa.dtypes)

#### Assumption 1.) Test for normality of the dependent variable (confidence_level) for any level of independent variable. 


a.) Visual inspection 

In [ ]:

#visual inspection of confidence level normality for native-English speaker population
dist_ne = sns.distplot(dfa_ne['confidence_level'], bins = 50,  color="skyblue", label="Confidence Level of Native English Speakers")
dist_ne.set_title('Distribution of Confidence Levels For Native English Speakers')
dist_ne.set_ylabel('number of students')
dist_ne.set_xlabel('confidence levels')
plt.legend()


In [ ]:
#visual inspection of confidence level normality for non-native speaker population
dist_nn = sns.distplot(dfa_nn['confidence_level'], bins = 50, color="red", label="Confidence Level of Non-Native English Speakers")
dist_nn.set_title('Distribution of Confidence Levels For Non_Native English Speakers')
dist_nn.set_ylabel('number of students')
dist_nn.set_xlabel('confidence levels')
plt.legend()

b.) QQ plots

In [ ]:
# QQ plots to check for normality of confidence level for any level of independent variable
from scipy import stats

plt.figure(1)
plt.subplot(2,2,1)

print('top Left: confidence level of non-native, top Right: confidence level of native')
print('bottow Left: confidence level of all')

nn_qq_plot = stats.probplot(dfa_nn['confidence_level'], plot=sns.mpl.pyplot)
plt.subplot(2,2,2)
ne_qq_plot = stats.probplot(dfa_ne['confidence_level'], plot=sns.mpl.pyplot)
plt.subplot(2,2,3)
all_qq_plot = stats.probplot(dfa['confidence_level'], plot=sns.mpl.pyplot)

##---------------un-comment to produce a single quantile plot (same as above)
#import numpy as np 
#import pylab 
#import scipy.stats as stats

##-----------------change the dataframe to show for a different population 
# stats.probplot(dfa_nn['confidence_level'], dist="norm", plot=pylab)
# pylab.show()

#### Assumption 2.) Test for equal variance of the dependent variable (confidence interval) across groups using the Levene test.
Levene test assumes normality. The null hypothesis is that the variances are equal. A significant result (p< 0.05) would indicate that we can reject the null hypothesis (variances are not equal).
If we rejecting the null hypothesis then we would be in violation of the homogeneity of equal variances. 
If we cannot reject the null hypothesis then we can assume the variances are equal and proceed.

In [ ]:
run_Levene_test(dfa_ne['confidence_level'],dfa_nn['confidence_level'])

#### Assumption 3.) Test that there is a linear relationship between the covariate (gender, prior experience) and the dependent variable (confidence level) for each level of the independent variable. **Can ignore if covariate is categorical variable.

To check this assumption we conduct a correlation analysis between the dependent variable(s) and the covariate(s). They should be highly correlated.** 

a.) We confirm that the correlation coefficient suggests there is a correlation (which it does in this case) between the covariates and the dependent variable.

b.) "More precisely one should test this assumption by obtaining and examining residuals plots comparing the stndardized residuals to the predicted values for the dependent variable." - http://web.mnstate.edu/malonech/Psy633/Notes/Mertler%20&%20Vannatta%20Ch.%205%20ANCOVA.pdf
This video explains how to analyze the residual plots: https://www.youtube.com/watch?v=iMdtTCX2Q70

c.) We visually confirm that the scatter plot of the dependent variable(s) and the covariate(s) show there is a correlation. 


In [ ]:
covariate = 'prior_exp'
dependent_var = 'confidence_level'

x_nn=dfa_nn[covariate]
y_nn=dfa_nn[dependent_var]

x_ne=dfa_ne[covariate]
y_ne=dfa_ne[dependent_var]

#create a scatter plot 
plt.plot(x_nn, y_nn, 'o')
plt.plot(x_ne, y_ne, '*')

#plot a first degree polynomial m = slope, b=intercept
m_nn, b_nn = np.polyfit(x_nn,y_nn, 1,)
plt.plot(x_nn, m_nn*x_nn + b_nn, label = "NNES", c = 'lightblue')

m_ne, b_ne = np.polyfit(x_ne,y_ne, 1,)
plt.plot(x_ne, m_ne*x_ne + b_ne, label = "NES", c = 'coral')
plt.xlabel(covariate)
plt.ylabel(dependent_var)
plt.legend(loc='best')
plt.title("Regression Slopes: Confidence Level vs Prior Experience of NNES and NES")
plt.show()

#return the slope of the line
print("The slope of " + dependent_var + " vs " + covariate + " for NES is "+ str(m_ne))
print("The slope of " + dependent_var + " vs " + covariate + " for NNES is "+ str(m_nn))



In [ ]:
#visual inspection for linearity
covariate = 'prior_exp'
dependent_var = 'confidence_level'
sns.regplot(x=dfa_ne[covariate], y=dfa_ne[dependent_var],scatter_kws={"color": "black"}, line_kws={"color": "red"}).set_title('Confidence Level vs Prior Experience of NES');

In [ ]:
##visual inspection for linearity
covariate = 'prior_exp'
dependent_var = 'confidence_level'
sns.regplot(x=dfa_nn[covariate], y=dfa_nn[dependent_var],scatter_kws={"color": "green"}, line_kws={"color": "coral"}).set_title('Confidence Level vs Prior Experience of NNES');

In [ ]:
 # residuals plot NES prior experience
covariate = 'prior_exp'
dependent_var = 'confidence_level'

X = dfa_ne['prior_exp']
Y = dfa_ne['confidence_level']

sns.residplot(X,Y, order = 1,color="g").set_title('Residuals Plot: CL vs PE for NES');

In [ ]:
# residuals plot NNES prior experience
covariate = 'prior_exp'
dependent_var = 'confidence_level'

X = dfa_nn['prior_exp']
Y = dfa_nn['confidence_level']

sns.residplot(X,Y, order = 1,color="black").set_title('Residuals Plot: CL vs PE for NNES');

In [ ]:

covariate = 'gender_num'
dependent_var = 'confidence_level'

x_ne=dfa_ne[covariate]
y_ne=dfa_ne[dependent_var]

x_nn = dfa_nn[covariate]
y_nn = dfa_nn[dependent_var]

#create a scatter plot 
plt.plot(x_ne, y_ne, 'o')
plt.plot(x_nn, y_nn, '*')

#plot a first degree polynomial m = slope, b=intercept
m_ne, b_ne = np.polyfit(x_ne,y_ne, 1)
m_nn, b_nn = np.polyfit(x_nn,y_nn, 1)
plt.plot(x_ne, m_ne*x_ne + b_ne, label = 'NES',c = 'blue')
plt.plot(x_nn, m_nn*x_nn + b_nn, label = 'NNES',c = 'red')
plt.xlabel("gender")
plt.ylabel("confidence level")
plt.legend(loc='best')
plt.title('Regression Slopes: Confidence Level vs Gender for NES and NNES')
plt.show()

#return the slope of the line
print("The slope of " + dependent_var + " vs " + covariate + " for NES is "+ str(m_ne))
print("The slope of " + dependent_var + " vs " + covariate + " for NNES is "+ str(m_nn))

In [ ]:
#visual inspection for linearity gender non natives
covariate = 'gender_num'
dependent_var = 'confidence_level'
sns.regplot(x=dfa_nn[covariate], y=dfa_nn[dependent_var],scatter_kws={"color": "black"}, line_kws={"color": "red"}).set_title('Confidence Level vs Gender for NNES');


In [ ]:
#visual inspection for linearity gender NES
covariate = 'gender_num'
dependent_var = 'confidence_level'
sns.regplot(x=dfa_ne[covariate], y=dfa_ne[dependent_var],scatter_kws={"color": "blue"}, line_kws={"color": "red"}).set_title('Confidence Level vs Gender for NES');

In [ ]:
# residuals plot NNES gender
covariate = 'gender_num'
dependent_var = 'confidence_level'

X = dfa_nn[covariate]
Y = dfa_nn[dependent_var]

sns.residplot(X,Y, order = 1,color="black").set_title('Residuals Plot: Confidence Level vs Gender for NNES');

In [ ]:
# residuals plot NES gender
covariate = 'gender_num'
dependent_var = 'confidence_level'

X = dfa_ne[covariate]
Y = dfa_ne[dependent_var]

sns.residplot(X,Y, order = 1,color="black").set_title('Residuals Plot: Confidence Level vs Gender for NES');

#### Assumption 5) Test for the homogeneity of regression slopes. 
Observe the regression slope plots above, if the lines do not cross then assumption is fulfilled.

This assumption states that the regression slopes (best fit lines between the covariate and the dependent variable are equal for each group of the analysis. If an independent variable-covariate interaction exists, the relationship between the covariate and the dependent variable is different at different levels of the independent variable. 
For example, we must check that the regression slope of the gender-confidence level is the same for both the non-native and native populations. 
http://web.mnstate.edu/malonech/Psy633/Notes/Mertler%20&%20Vannatta%20Ch.%205%20ANCOVA.pdf



In [ ]:

#covariates should have equal mean scores across the factor groups.
#covariates are gender and prior experience
cov_1 = 'gender_num'
cov_2 = 'prior_exp'

#getting the means of each covariate for each factor level
dfa_ne_cov_1 = dfa_ne[cov_1].mean()
dfa_nn_cov_1 = dfa_nn[cov_1].mean()
dfa_ne_cov_2 = dfa_ne[cov_2].mean()
dfa_nn_cov_2 = dfa_nn[cov_2].mean()

print("covariate: " + cov_1 + " mean for native speakers is "+ str(dfa_ne_cov_1))
print("covariate: " + cov_1 + " mean for non-native speakers is " + str(dfa_nn_cov_1))

t_test_cov_1 = ttest_ind(dfa_ne[cov_1],dfa_nn[cov_1], equal_var=False)

if (t_test_cov_1.pvalue < 0.05):
  print('Reject the null hypothesis that the means of '+ cov_1 + ' are equal for native and non-native.')
  print(str(t_test_cov_1.pvalue) + " < 0.05")
  print('T-test results for average ' + cov_1 + ' between native and non-native:')
  print(str(t_test_cov_1))
else:
  print("We cannot reject the null hypotheis that the means for " + cov_1 + ' are equal for native and non-native')
  print(str(t_test_cov_1.pvalue) + ' > 0.05')
  print('T-test results for average ' + cov_1 + ' between native and non-native:')
  print(str(t_test_cov_1))

print('-----------------------------------------------------------------------')
# now checking prior experience

print("covariate: " + cov_2 + " mean for native speakers is "+ str(dfa_ne_cov_2))
print("covariate: " + cov_2 + " mean for non-native speakers is "+ str(dfa_nn_cov_2))

t_test_cov_2 = ttest_ind(dfa_ne[cov_2],dfa_nn[cov_2], equal_var=False)

if (t_test_cov_2.pvalue < 0.05):
  print("Reject the null hypothesis that the means of " + cov_2 + " are equal for native and non-native.")
  print(str(t_test_cov_2.pvalue) + "< 0.05")
  print('T-test results for average ' + cov_2 + ' between native and non-native:')
  print(str(t_test_cov_2))
else:
  print("We cannot reject the null hypotheis that the means for " + cov_2 + " are equal for native and non-native")
  print(str(t_test_cov_2.pvalue) + '> 0.05')
  print('T-test results for average ' + cov_2 + ' between native and non-native:')
  print(str(t_test_cov_2))



In [ ]:
!pip install pingouin 

# x = 1

#### ANCOVA 
Rows with missing values are automatically removed (listwise deletion) by the ancova function as stated in the documentation. 

info on eta squared: 
the percentage of variance in the dependent variable accounted for by the independent variable (similar to r^2)

partial eta squared is the same as eta squared when you only have one independent variable
https://www.statisticshowto.com/eta-squared/

to analyze the ancova table:
https://www.sheffield.ac.uk/polopoly_fs/1.531229!/file/MASH_ANCOVA_SPSS.pdf

In [ ]:

#checking the interaction of the independent variable with the covariates
import pingouin as pg
from pingouin import ancova

c1 = 'gender_num'
c2 = 'prior_exp'
d_var = 'confidence_level'

# we select partial eta squared because 
ancova_result = ancova(data=dfa, dv= d_var, covar=[ c1, c2], between='native_bool_num', effsize="np2")

display(ancova_result)


The ANCOVA Results indicate that we can reject the hypothesis that english language fluency leads to the same confidence level after controlling for gender and prior experience.

##### Multiple Regression Results

The ANCOVA assumption were fulfilled and ANCOVA was performed, but we proceed with exploring Multiple Regression. When using multiple regression it is ideal that the variables gender num, native bool num, and prior experience not be correlated with each other. This has not been checked.
**non-imputed data:** 
**gender num coeff 0.24 pval .00429** ,
**native bool num 0.03 pval 0.7,**
**prior exp 0.42 pval 5.35 e-28** 

0.42 is an estimate of the expected increase in confidence level corresponding to a unit increase in prior experience when gender_num and native_bool_num are held constant. For example, if a student's prior experience was increased by 1, then their confidence level would increase by 0.42, while other variables are constant. **Prior experience has the highest impact on confidence level, followed by gender, and lastly English fluency (not significant)**. 

**imputed data:**
gender num coeff 0.23,
native bool num 0.04,
prior exp 0.42.

When using imputed data the native bool influence increases and gender decreases slightly. 



In [ ]:
#run this section to check multiple regression with imputation
dfm = dfa.copy(deep=True)

#coding the native_bool column Native = 1, Non-Native = 0
dfm['native_bool_num'] = ''
dfm.loc[(dfm['native_bool'] == True ), ['native_bool_num']]= 1
dfm.loc[(dfm['native_bool'] == False ), ['native_bool_num']]= 0
dfm[['native_bool_num']] = dfm[['native_bool_num']].apply(pd.to_numeric)

#coding the gender column male - 3, female - 2, non-binary - 1
dfm=dfm.dropna(subset=['gender']) #drop empty
dfm['gender_num'] = 0
dfm.loc[(dfm['gender'] == 'Male' ), ['gender_num']]= 3
dfm.loc[(dfm['gender'] == 'Female' ), ['gender_num']]= 2
dfm.loc[(dfm['gender'] == 'Non-Binary' ), ['gender_num']]= 1
dfm[['gender_num']] = dfm[['gender_num']].apply(pd.to_numeric)


##----------imputation-----------
dfm = impute_from_distrib(dfm,'gender_num')
dfm = impute_from_distrib(dfm,'prior_exp')
# dfm = impute_from_distrib(dfm,'confidence_level')

In [ ]:

# #---- uncomment this section to check multiple regression using IMPUTED data ------
#----------imputation-----------
dfm = impute_from_distrib(dfm,'gender_num')
dfm = impute_from_distrib(dfm,'prior_exp')
dfm = impute_from_distrib(dfm,'confidence_level')
lm = pg.linear_regression(dfa[['gender_num', 'native_bool_num', 'prior_exp']], dfa['confidence_level'], )
lm 

# #----- uncomment this section to check multiple regression using NON IMPUTED data --------
# dfm=dfm.dropna(subset=['prior_exp'])
# lm = pg.linear_regression(dfm[['gender_num', 'native_bool_num', 'prior_exp']], dfm['confidence_level'], )
# lm

In [ ]:
#This code provides the important coefficients for our variables.
dfa=dfa.dropna(subset=['prior_exp'])
X= dfa[['gender_num', 'native_bool','prior_exp']]
Y = dfa['confidence_level']

from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(X, Y)
print(regr.coef_)

## Q: Is the prior experience of Native English Speakers different from non-native English Speakers?

In [ ]:
dfp = dfc_full.copy(deep=True)

# describe_col(dfp,'native_bool')
# dfp = dfp.dropna(subset=['native_bool'])

df_d = df_d.rename(columns = {"Gender (Binary)":'gender'})
dfp = (dfp.set_index('id').join(df_d.set_index('DeID') ,how='left'))

# ##-----------Check for empty values of gender and prior experience
# describe_col(dfp,'gender')
# describe_col(dfp,'prior_exp')

# ##-----------Check if result changes with imputation of gender
# #Since there are 37 rows empty for gender and 2 empty for prior experience we will impute all
dfp = impute_from_distrib(dfp, 'gender')
# describe_col(dfp,'gender')

# #-----------Check if result changes with dropping empty rows of gender
# dfp=dfp.dropna(subset=['gender']) #drop empty
# describe_col(dfp,'gender')

#-----------Check if result changes with imputation of prior exp
dfp = impute_from_distrib(dfp, 'prior_exp')
#describe_col(dfp,'prior_exp')

# #-----------Check if result changes with dropping empty rows of prior exp
# dfp=dfp.dropna(subset=['prior_exp']) #drop empty


#coding the native_bool column Native = 1, Non-Native = 0
dfp['native_bool_num'] = ''
dfp.loc[(dfp['native_bool'] == True ), ['native_bool_num']]= 1
dfp.loc[(dfp['native_bool'] == False ), ['native_bool_num']]= 0
dfp[['native_bool_num']] = dfp[['native_bool_num']].apply(pd.to_numeric)

#coding the gender column male - 3, female - 2, non-binary - 1
dfp['gender_num'] = 0
dfp.loc[(dfp['gender'] == 'M' ), ['gender_num']]= 3
dfp.loc[(dfp['gender'] == 'F' ), ['gender_num']]= 2
dfp.loc[(dfp['gender'] == 'Non-Binary' ), ['gender_num']]= 1
dfp[['gender']] = dfp[['gender_num']].apply(pd.to_numeric)
print("total Students is " + str(dfp.shape[0]))


##separate dataframes for independent variable 
dfp_nn = dfp[dfp['native_bool_num'] == 0 ]
dfp_ne = dfp[dfp['native_bool_num'] == 1 ]
print("total NN Students is " + str(dfp_nn.shape[0]))
print("total NE Students is " + str(dfp_ne.shape[0]))

# describe_col(dfa,'gender_num')
# display(dfa)
#print out the data types
# print(dfa.dtypes)



In [ ]:
dfp_ne_mean_p = dfp_ne['prior_exp'].mean()
dfp_nn_mean_p = dfp_nn['prior_exp'].mean()


print("prior experience mean for native speakers is "+ str(dfp_ne_mean_p))
print("prior experience mean for non-native speakers is " + str(dfp_nn_mean_p))

t_test_cov_1 = ttest_ind(dfp_ne['prior_exp'],dfp_nn['prior_exp'], equal_var=False)

if (t_test_cov_1.pvalue < 0.05):
  print('Reject the null hypothesis that the means of prior experience are equal for native and non-native.')
  print(str(t_test_cov_1.pvalue) + " < 0.05")
  print('T-test results for average prior experience between native and non-native:')
  print(str(t_test_cov_1))
else:
  print('Decision: Fail to Reject that the means for prior experience are equal for native and non-native')
  print(str(t_test_cov_1.pvalue) + ' > 0.05')
  print('T-test results for average prior experience between native and non-native:')
  print(str(t_test_cov_1))
    
print('----------------Mann-Whitney U test---------------')
#input non-natives then natives
run_Mann_Whitney_test(dfp_nn['prior_exp'],dfp_ne['prior_exp'])

print('-----------------------------------------------------------------------')
# now checking prior experience
dfp_ne_mean_gender = dfp_ne['gender_num'].mean()
dfp_nn_mean_gender = dfp_nn['gender_num'].mean()


print("gender mean for native speakers is "+ str(dfp_ne_mean_gender))
print("gender mean for non-native speakers is " + str(dfp_nn_mean_gender))

t_test_cov_2 = ttest_ind(dfp_ne['gender_num'],dfp_nn['gender_num'], equal_var=False)

if (t_test_cov_2.pvalue < 0.05):
  print("Reject the null hypothesis that the means of gender are equal for native and non-native.")
  print(str(t_test_cov_2.pvalue) + "< 0.05")
  print('T-test results for average gender between native and non-native:')
  print(str(t_test_cov_2))
else:
  print("Decision: Fail to Reject that the means for gender are equal for native and non-native")
  print(str(t_test_cov_2.pvalue) + '> 0.05')
  print('T-test results for average gender between native and non-native:')
  print(str(t_test_cov_2))

print('----------------Mann-Whitney U test---------------')
#input non-natives then natives
run_Mann_Whitney_test(dfp_nn['gender'],dfp_ne['gender'])

We fail to reject that the mean of gender and prior expeience is equal for native and non native

In [ ]:
df_cs = dfc_full.copy(deep=True)

# describe_col(dfp,'native_bool')
# dfp = dfp.dropna(subset=['native_bool'])

df_d = df_d.rename(columns = {"Gender (Binary)":'gender'})
df_cs = (df_cs.set_index('id').join(df_d.set_index('DeID') ,how='left'))

# ##-----------Check for empty values of cs experience
# describe_col(df_cs,'cs_exp')

#There are 9 empty rows of cs experience

# #-----------Check if result changes with dropping empty rows of cs exp
# df_cs=df_cs.dropna(subset=['cs_exp']) #drop empty
# describe_col(df_cs,'cs_exp')

##-----------Check if result changes with imputation of prior exp
df_cs = impute_from_distrib(df_cs, 'cs_exp')
describe_col(df_cs,'cs_exp')

#coding the native_bool column Native = 1, Non-Native = 0
df_cs['native_bool_num'] = ''
df_cs.loc[(df_cs['native_bool'] == True ), ['native_bool_num']]= 1
df_cs.loc[(df_cs['native_bool'] == False ), ['native_bool_num']]= 0
df_cs[['native_bool_num']] = df_cs[['native_bool_num']].apply(pd.to_numeric)

#coding the gender column male - 3, female - 2, non-binary - 1
df_cs['gender_num'] = 0
df_cs.loc[(df_cs['gender'] == 'M' ), ['gender_num']]= 3
df_cs.loc[(df_cs['gender'] == 'F' ), ['gender_num']]= 2
df_cs.loc[(df_cs['gender'] == 'Non-Binary' ), ['gender_num']]= 1
df_cs[['gender']] = df_cs[['gender_num']].apply(pd.to_numeric)
print("total Students is " + str(df_cs.shape[0]))


##separate dataframes for independent variable 
dfp_nn = df_cs[df_cs['native_bool_num'] == 0 ]
dfp_ne = df_cs[df_cs['native_bool_num'] == 1 ]
print("total NN Students is " + str(dfp_nn.shape[0]))
print("total NE Students is " + str(dfp_ne.shape[0]))

# describe_col(dfa,'gender_num')
# display(dfa)
#print out the data types
# print(dfa.dtypes)






In [ ]:
#input is a fully imputed dataframe
def get_cs_exp_frequency(df_input,col):
    """Gets the a frequency value for the cs experience"""
    #initializing cs experince num col and making copy of input col
    df_input['cs_exp_num'] = 0

    for i in df_input[col]:
        df_input['cs_exp_num'] = df_input[col].apply(lambda x: x.count('AP CS A'))
        df_input['cs_exp_num'] += df_input[col].apply(lambda x: x.count('CS courses at a college or university AS A STUDENT AT THAT COLLEGE OR UNIVERSITY'))
        df_input['cs_exp_num'] += df_input[col].apply(lambda x: x.count('Took one of more CS courses at a college or university AS A HIGH SCHOOL STUDENT '))
        #df_input['cs_exp_num'] += df_input[col].apply(lambda x: x.count('AP CS Principles'))
    return df_input

In [ ]:
df_cs_exp = get_cs_exp_frequency(df_cs,'cs_exp')

df_cs_exp_ne = df_cs_exp[df_cs_exp['native_bool']==True]
df_cs_exp_nn = df_cs_exp[df_cs_exp['native_bool']==False]
#display(df_cs_exp_ne)
#describe_col(df_cs_exp_ne,'cs_exp_num')

print("cs experience mean for native speakers is " +  str(df_cs_exp_ne['cs_exp_num'].mean()))
print("cs experience mean for non-native speakers is " + str(df_cs_exp_nn['cs_exp_num'].mean()))

t_test_cov_1 = ttest_ind( df_cs_exp_ne['cs_exp_num'], df_cs_exp_nn['cs_exp_num'], equal_var=False)

if (t_test_cov_1.pvalue < 0.05):
  print('Reject the null hypothesis that the means of cs experience are equal for native and non-native.')
  print(str(t_test_cov_1.pvalue) + " < 0.05")
  print('T-test results for average cs experience between native and non-native:')
  print(str(t_test_cov_1))
else:
  print('Decision: Fail to Reject that the means for cs experience are equal for native and non-native')
  print(str(t_test_cov_1.pvalue) + ' > 0.05')
  print('T-test results for average cs experience between native and non-native:')
  print(str(t_test_cov_1))
    
print('----------------Mann-Whitney U test---------------')
#input non-natives then natives
run_Mann_Whitney_test(df_cs_exp_nn['cs_exp_num'], df_cs_exp_ne['cs_exp_num'])



In [ ]:
df_new = df_og.copy(deep = True)

df_new=df_new.dropna(subset=['transfer']) #drop empty

df_new['transfer_bool']= False

df_new.loc[(df_new['transfer']=='Yes'),['transfer_bool']] = True

#display(df_new)
#df_new[df_new['transfer']== 'Yes']
# #df_new.loc[(df_new['english_fluency'] == 3), ['native_bool']]= True 
# display(df_new)
# #coding the native_bool column Native = 1, Non-Native = 0

df_new['transfer_bool_num'] = ''
df_new.loc[(df_new['transfer_bool'] == True ), ['transfer_bool_num']]= 1
df_new.loc[(df_new['transfer_bool'] == False ), ['transfer_bool_num']]= 0
df_new[['transfer_bool_num']] = df_new[['transfer_bool_num']].apply(pd.to_numeric)

df_ne = df_new[df_new['native_bool']==True]
df_nn = df_new[df_new['native_bool']==False]

describe_col(df_nn,'transfer_bool_num')

t_test= ttest_ind(df_nn['transfer_bool_num'],df_ne['transfer_bool_num'], equal_var=False)
print(t_test)


## Q: Do non-native english students have a different minimum grade needed to be satisfied than native english speakers? 

Using the [grading system to quantify grades](https://blink.ucsd.edu/instructors/academic-info/grades/system.html#:~:text=Find%20out%20about%20the%20UCSD,and%20how%20to%20interpret%20grades.&text=The%20grade%20of%20A%2B%2C%20when,and%20minus%20suffixes%20is%20optional.)

In [ ]:
dfge = df.copy()
dfge['ordinal_min_grade'] = ''
def quantify_expected_grade(input_dataframe): 
    """Changed expected grade to numbers A+ = 4.0, etc """
    input_dataframe.loc[(input_dataframe['min_grade_expected'] ==  'A+'), ['ordinal_min_grade']]= 4.3
    input_dataframe.loc[(input_dataframe['min_grade_expected'] ==  'A'), ['ordinal_min_grade']]= 4.0
    input_dataframe.loc[(input_dataframe['min_grade_expected'] ==  'A-'), ['ordinal_min_grade']]= 3.7
    input_dataframe.loc[(input_dataframe['min_grade_expected'] ==  'B+'), ['ordinal_min_grade']]= 3.3
    input_dataframe.loc[(input_dataframe['min_grade_expected'] ==  'B'), ['ordinal_min_grade']]= 3.0
    input_dataframe.loc[(input_dataframe['min_grade_expected'] ==  'B-'), ['ordinal_min_grade']]= 2.7
    input_dataframe.loc[(input_dataframe['min_grade_expected'] ==  'C+'), ['ordinal_min_grade']]= 2.3
    input_dataframe.loc[(input_dataframe['min_grade_expected'] ==  'C'), ['ordinal_min_grade']]= 2.0
    input_dataframe.loc[(input_dataframe['min_grade_expected'] ==  'C-'), ['ordinal_min_grade']]= 1.7
    input_dataframe.loc[(input_dataframe['min_grade_expected'] ==  'D'), ['ordinal_min_grade']]= 1
    input_dataframe[["ordinal_min_grade"]] = input_dataframe[["ordinal_min_grade"]].apply(pd.to_numeric)
    return input_dataframe 

quantify_expected_grade(dfge)

dfge = impute_from_distrib(dfge, 'ordinal_min_grade')
describe_col(dfge, 'ordinal_min_grade')

mean_expected_grade = get_single_mean(dfge[dfge['native_bool'] == True], 'ordinal_min_grade')
mean_expected_grade_non_native = get_single_mean(dfge[dfge['native_bool'] == False], 'ordinal_min_grade')

print("The mean min grade to satisfy native english speakers is " + str(mean_expected_grade))
print("The mean min grade to satisfy non-native english speakers is " + str(mean_expected_grade_non_native))

print("---------------------T-Test---------------------")
run_t_test(dfge[dfge['native_bool'] == True].ordinal_min_grade, dfge[dfge['native_bool'] == False].ordinal_min_grade)
print("---------------------Welch Test-------------------")
run_welch_test(dfge[dfge['native_bool'] == True].ordinal_min_grade, dfge[dfge['native_bool'] == False].ordinal_min_grade)


dfge_heatmap = dfge.copy()
dfge_heatmap['gender_ordinal']=dfge_heatmap['gender'].astype('category').cat.codes
# dfge_heatmap['transfer']=dfge_heatmap['transfer'].astype('category').cat.codes
# dfge_heatmap['race']=dfge_heatmap['race'].astype('category').cat.codes
plt.rc('figure', figsize=( 5,2)  , dpi=200)
plt.rc('font', size=5)   # font size
plt.xlabel("Values on X axis")
sns.heatmap(dfge_heatmap.corr(), annot = True, cmap= 'coolwarm', square=True, linewidths=.5,vmin=-1, vmax=1)
# dfge_heatmap

In [ ]:

dfge = df.copy()
grade_e_counts = (dfge[dfge['native_bool'] == True ].min_grade_expected.value_counts(normalize = True).sort_index())
grade_e_counts_nn = (dfge[dfge['native_bool'] == False ].min_grade_expected.value_counts(normalize = True).sort_index())
print("NATIVE")
print(grade_e_counts)
print("NON-NATIVE")
print(grade_e_counts_nn)
list_grade_e_counts_n = [0.007407, 0.266667, 0.288889, 0.103704, 0.192593, 0.074074, 
      0.014815, 0.022222, 0.029630, 0 ]
list_grade_e_counts_nn = [0.026549, 0.345133, 0.398230, 0.061947, 0.115044, 0.035398, 0,
      0.008850,0,  0.008850, ] 
graph_stack_grade_e = pd.DataFrame(index= ['Native', 'Non-Native'], columns= ['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-' , 'D'])
graph_stack_grade_e.loc['Native'] = (list_grade_e_counts_n ) # adding a row
graph_stack_grade_e.loc['Non-Native'] = (list_grade_e_counts_nn ) # adding a row
plt.style.use('seaborn-white')   # seaborn custom plot style
plt.rc('figure', dpi=100, figsize=(7, 5))   # set default size/resolution
plt.rc('font', size=12)   # font size
graph_stack_grade_e.plot.barh(stacked=True, colormap='tab20c').legend(bbox_to_anchor=(1, 0.5))
plt.title('CSE12 Min Grade Expected')
plt.xlabel('Percentage of students')
plt.ylabel('Type of English Speaker')
graph_stack_grade_e

## Q: What is the strongest correlation coefficient that is associated with confidence level?  

.cat.codes converts category from a string representation into an integer representation

In [ ]:
dfg_cat = dfg.copy()
dfg_cat['gender_ordinal']=dfg_cat['gender'].astype('category').cat.codes
dfg_cat['transfer']=dfg_cat['transfer'].astype('category').cat.codes
dfg_cat['race']=dfg_cat['race'].astype('category').cat.codes
dfg_cat['ethnicity']=dfg_cat['ethnicity'].astype('category').cat.codes
plt.rc('figure', figsize=( 6,3)  , dpi=200)
plt.rc('font', size=5)   # font size
plt.xlabel("Values on X axis")
sns.heatmap(dfg_cat.corr(), annot = True, cmap= 'coolwarm', square=True, linewidths=.5,vmin=-1, vmax=1)

df_corr = dfg_cat.corr(method ='pearson')
corr_confidence_level = df_corr['confidence_level'].sort_values(ascending=False)
corr_grade = df_corr['overall_grades'].sort_values(ascending=False)
print(corr_confidence_level)
print(corr_grade)

## A: The strongest correlation coefficient is prior experience. 

# <a id='section_RQC'> Research Question Confidence Level + Grades </a>   

[- Return](#toc) 


### Does confidence level correlate with grade earned?


### Is there a significant difference between the average confidence level of non-native and native english speaker? 

In [ ]:
    # histogram of the height
dfg_n.confidence_level.plot(kind='hist', color='lightblue', edgecolor='black', )
dfg_nn.confidence_level.plot(kind='hist', color='orange', edgecolor='black', )
plt.title('Distribution of Confidence Level of Native and Non-Native English Speakers' )
plt.xlabel('Confidence Level', size=12)
plt.ylabel('Frequency', size=12)


# sns.catplot(y="confidence_level", hue="native_bool", kind="count",
#             palette="pastel", edgecolor=".6",
#             data= dfg);



In [ ]:
print("Getting results for non-imputed data")
dfg_n = dfg[dfg['native_bool'] == True]
dfg_nn = dfg[dfg['native_bool'] == False]

get_single_mean(dfg_n, 'confidence_level')
get_single_mean(dfg_nn, 'confidence_level')
print("The variance for native speaker overall grade score is " + str(np.var(dfg_n.confidence_level)))
print("The variance for non-native speaker overall grade score is " + str(np.var(dfg_nn.confidence_level)))

ttest_ind(dfg_n['confidence_level'], dfg_nn['confidence_level'], equal_var=False,nan_policy = 'omit')

In [ ]:
print("Getting results for imputed data")
dfg = impute_from_distrib(dfg, 'confidence_level')
dfg_n = dfg[dfg['native_bool'] == True]
dfg_nn = dfg[dfg['native_bool'] == False]

get_single_mean(dfg_n, 'confidence_level')
get_single_mean(dfg_nn, 'confidence_level')
print("The variance for native speaker overall grade score is " + str(np.var(dfg_n.confidence_level)))
print("The variance for non-native speaker overall grade score is " + str(np.var(dfg_nn.confidence_level)))

ttest_ind(dfg_n['confidence_level'], dfg_nn['confidence_level'], equal_var=False,nan_policy = 'omit')

### <a id='section_RQC_conclusion'> Research Question Conclusion On Confidence Level </a>  

 [- Return](#toc) 

After running the t-test and getting a p-value of 0.04 which is less than 0.05, we reject the null hypothesis of average identical confidence levels of non-native english speaker students and native english speaker students 


## General On Multiple Factors 

In [ ]:
ax = sns.regplot(x="english_fluency", y='overall_grades', data= dfg)
correlation = dfg['english_fluency'].corr(dfg['overall_grades'])
correlation

In [ ]:
for x in dfg.columns:
    try: 
        print("The correlation between " + x + " and overall grades is " + str(dfg[x].corr(dfg['overall_grades'])))
    except:
        pass
    
# from scipy.stats import ks_2samp
# ks_2samp(dfg_n.overall_grades, dfg_nn.overall_grades)
# ks_2samp(dfg_n.confidence_level, dfg_nn.confidence_level)




In [ ]:
# df_full['ethnicity_bool'] = df_full.ethnicity == 'Hispanic or Latino/a'
# print("The correlation between " + x + " and ethnicity bool is " + str(df_full['native_bool'].corr(df_full['ethnicity_bool'])))

# df_full[['ethnicity_bool', 'ethnicity']]


# df_full

# hmm2 = df[(df['Race'] != 'Human')  & (df['Publisher'] != 'DC Comics' )  & (df['Publisher'] != 'Marvel Comics' ) ]




# <a id='section_RQC_conclusion'> Research Question Get Resource </a>  

[- Return](#toc) 




### Question 1) Is there a significant difference between the average weekly percentage of NN and NE students who used online resources over the course of the quarter


###Question 2) Is there a significant difference between the average weekly percentage of NN and NE students who used in-person resources over the course of the quarter

#### A note about imputation

The resource columns are imputed using the impute_from_distrib function to fill in the empty response data. This was we differentiate between those students who explicitly stated that they did not use a resource and those who left the question blank.

In [ ]:
for col in df_full.columns:
    if '_resource' in col:
      print(describe_missing(col))
      

In [ ]:

for col in df_full.columns:
    if '_resource' in col:
        df_full = impute_from_distrib(df_full, col)
#a copy of the imputed data is made to be used below
df_full_2 = df_full.copy()
df_full_2['id'] = df_full_2.index

df_res_frequency = df_full.copy()
df_res_frequency['id'] = df_full_2.index
#print(df_res_frequency.columns)


**function get_res_test:**  
takes in a df, a list of relevant columns from the input df; a search word used to get the colums that contain it; english_fluency boolean (True for NE or False for NN). **Returns** a dataframe containing the percentage of students for each category per week. Columns include: week, in-person, online and both.
 
note: input data must be imputed prior. Both NN and NE categories of students are calculated separately.

In [ ]:
#bool english_fluency True if NE(Native Eng Speaker), False if NN(Non-Native Eng Speaker)

def get_res_test(df_input, list_standard, search_word, english_fluency): 
   
    #Get only column names we want to keep in new dataframe
    keep_titles = list_standard
    keep_titles += [col for col in df_input.columns if search_word in col ]

    #new dataframe including columns specified in keep_titles
    df_r = df_input[keep_titles]

    #new dataframe for either native or non-native
    if english_fluency == True:
        df_get_resources = (df_r[df_r['native_bool'] ])
        num_responses = df_get_resources.shape[0]
        print("The total number of NE students is : " + str(num_responses))
    else:
        df_get_resources = (df_r[df_r['native_bool']==False])
        num_responses = df_get_resources.shape[0]
        print("The total number of NN students is : " + str(num_responses))

    count_ip = 0; count_or = 0;count_both = 0;count_none = 0;count_either = 0;count_fr = 0
 
    #dataframe containing proportions
    df_per_res = pd.DataFrame()
     
    # Yields a tuple of column name and series for each column in the dataframe
    #iterating through the weeks    
    for (columnName, columnData) in df_get_resources.iteritems():
        simple_list = [[]]
        if '_resource' in columnName:
            
            #check every week for resource used per person and creating a boolean column for each 
            # online vs in-person cols
            ip_tutor = columnData.str.contains(pat = 'A tutor')
            ip_ta = columnData.str.contains('TA')
            ip_peer = columnData.str.contains('My peer(s)',regex=False)
            ol_discuss = columnData.str.contains('Discussion')
            ol = columnData.str.contains('Stack',case=False,regex=False)|columnData.str.contains('internet',case=False,regex=False)|columnData.str.contains('Java', case = False,regex = False)|columnData.str.contains('looked up documentation')
            
            #redundant
            peers_pair = columnData.str.contains('as pair programming/joint assignment submission',regex=False)&columnData.str.contains('version')
            peers_own = columnData.str.contains('version')
            ol_discuss_post = columnData.str.contains('I posted',regex=False)
            ol_discuss_read = columnData.str.contains('reading responses',regex=False)
            
            #other categories
            ip_friends = columnData.str.contains('friend')
            none = columnData.str.contains('I did not seek help')
            
            #making a df of the boolean columns online vs in-person
            res_bool = pd.DataFrame({'tu' : ip_tutor, 'TA' : ip_ta, 'peer': ip_peer,'disc':ol_discuss,'online':ol,'friends':ip_friends,'none':none})
            
            num_stud = res_bool.shape[0]
                
            count_ip = 0; count_or = 0;count_both = 0;count_none = 0;count_either = 0;count_fr = 0
            list_ip =[];list_or=[];list_both=[]
            
            #checking each index or row for boolean value
            for index, row in res_bool.iterrows():
                #*********************************************print([row])
                #*********************************************print([index])
                
                if row['tu']|row['TA']|row['peer']== True:
                    count_ip += 1
                    #*****************************************print(count_ip)
               
                if row['disc']|row['online'] == True:
                    count_or += 1
                    
                if (row['tu']|row['TA']|row['peer']== True) & (row['disc']|row['online'])== True:
                    count_both += 1
                    
                if (row['tu']|row['TA']|row['peer']== True) | (row['disc']|row['online'])|(row['tu']|row['TA']|row['peer']== True) & (row['disc']|row['online']) == True:
                    count_either += 1
                    
                if (row['none']== True) == True:
                    count_none += 1
                if (row['friends']== True) == True:
                    count_fr += 1

            #getting the percentages of online resource, in person and both (online and in-person) 
            prop_both = (count_either/num_responses)*100
            prop_or = (count_or/num_responses)*100
            prop_ip = (count_ip/num_responses)*100
            #checking proportions
            #print("proportions per week " + "in person: "+ str(prop_ip) +" online: " + str(prop_or)+ " both: " + str(prop_both))
            #row to append
            
            #checking for the fluency to assign column names
            if english_fluency == True:
                new_row = {'week': columnName, 'NE in-person': prop_ip, 'NE online': prop_or, 'NE both':prop_both}
                df_per_res = df_per_res.append(new_row,ignore_index=True)
                df_per_res.set_index('week')
            else: 
                new_row = {'week': columnName, 'NN in-person': prop_ip, 'NN online': prop_or, 'NN both':prop_both}
                df_per_res = df_per_res.append(new_row,ignore_index=True)
                df_per_res.set_index('week') 

   
    return df_per_res



####A note about categorization of resources

Resources were categorized into two categories: 
(1) human interaction - TA, tutor, and peers (2) non-human interaction - discussion board and online resources (3) students who used both

(1)
note: "friends outside of class" category was excluded in because the language being used is uknown. The "peers (pair programming)" and "peers (own version)" categories were excluded because it was assumed that students are either working on their own version, or pair programming, but not both, hence only the "peers" category counts.

(2) 
note: specific categories of discussion board were excluded and only the general 'discussion board' category
was included along with any other online resource

In [ ]:
#NE 
df_ne_resource = get_res_test(df_full_2,['id', 'native_bool' ], '_resource',True)
display(df_ne_resource)
#NN 
df_n_resource= get_res_test(df_full_2,['id', 'native_bool' ], '_resource', False)

#merging the dfs for both categories and getting the mean and variance
result = pd.concat([df_ne_resource,df_n_resource],axis=1, join='inner')
mean = result.mean()
var = result.var()

print('the mean of each category over all weeks: \n' + str(mean))
print("the variance of each column is: \n" + str(var))
print("standard deviation ratio of the NN and NE both: " + str(math.sqrt(var[3])/math.sqrt(var[0])))
print("standard deviation ratio of the NN and NE in-person: " + str(math.sqrt(var[4])/math.sqrt(var[1])))
print("standard deviation ratio of the NN and NE online: " + str(math.sqrt(var[5])/math.sqrt(var[2])))
#independent t-test
print("t-test: both online and in-person resources: " + str(ttest_ind(df_n_resource['NN both'], df_ne_resource['NE both'],equal_var = False)))
print("t-test: online resources only: " + str(ttest_ind(df_n_resource['NN online'], df_ne_resource['NE online'],equal_var=False)))
print("t-test: in-person resources only: " + str(ttest_ind(df_n_resource['NN in-person'], df_ne_resource['NE in-person'],equal_var=False)))

#colums are rearranged for better order in the graphical representation
data = {'week':df_ne_resource['week'],'NN percentage of in-person resources':result['NN in-person'], 
        'NE percentage of in-person resources':result["NE in-person"], 
        'NN percentage of online resources':result["NN online"], 'NE percentage of online resources':result['NE online']}
result_col_adjust = pd.DataFrame(data)
result_col_adjust.set_index(df_ne_resource['week'])

#to display the resulting columns
#display(result_col_adjust)

#plot style/hexcolors
color_list = ['#229954', '#E67E22', '#72D9CE', '#EEB7A1']
ax = result_col_adjust.plot(kind='bar', color=color_list)

ax.legend(loc='center left', bbox_to_anchor=(1.0, 0.5),fontsize = 10)#loc=1, fontsize=9)
plt.title("Percentage of non-native vs. native English speakers who used online and in-person resources used by",fontsize = 12)
plt.xlabel("weeks of instruction",fontsize = 10)
plt.ylabel("percentage of students (who used resource)",fontsize = 10)

#### T-test and General Trends
**Independent t-test:** where the mean we care about is percentage of students who used a resource type over 9 weeks. 

(3 tests) - Is there a significant difference between the average number of NN and NE students who used a) online resources b) in-person resources c) both resources simultaneously

Ho: The null hypothesis is that the average mean from the two independent groups (NN and NE) are equal.
H1: The means are not equal 

We cannot reject the null hypothesis

**General Trends** 
Generally both categories of students seek out the in-person resources.


#### Correlations Relating English Language Fluency to Grades and Resource Use Frequency 

**function get_res_frequency_from_weeks:**  
takes in an df, where every column related to resource in the df should be fully imputed  **Returns** a dataframe containing the original resource responses for every week, a concatenated column, and columns containing the frequency with which each each student in the df used a particular resource over the course of the quarter.
 


In [ ]:
#input is a fully imputed dataframe
def get_res_frequency_from_weeks(df_input):
    """Gets the frequency that each student (NN and NE) used a particular resource"""
    
    df_input = df_input[['time', 'native_bool', 'english_fluency','gender',
                           'confidence_level','transfer','prior_exp','wk2_resource', 
                            'wk3_resource','wk4_resource', 'wk5_resource', 'wk6_resource', 
                              'wk7_resource','wk8_resource', 'wk9_resource']]

    
    #copying each column and concatenating the resource strings for each student
    copy_3 = df_input['wk3_resource'].copy()
    copy_4 = df_input['wk4_resource'].copy()
    copy_5 = df_input['wk5_resource'].copy()
    copy_6 = df_input['wk6_resource'].copy()
    copy_7 = df_input['wk7_resource'].copy()
    copy_8 = df_input['wk8_resource'].copy()
    copy_9 = df_input['wk9_resource'].copy()
    df_input["concat_resource"]= df_input['wk2_resource'].str.cat(copy_3, sep ="**")
    df_input["concat_resource"]= df_input["concat_resource"].str.cat(copy_4, sep ="**")
    df_input["concat_resource"]= df_input["concat_resource"].str.cat(copy_5, sep ="**")
    df_input["concat_resource"]= df_input["concat_resource"].str.cat(copy_7, sep ="**")
    df_input["concat_resource"]= df_input["concat_resource"].str.cat(copy_8, sep ="**")
    df_input["concat_resource"]= df_input["concat_resource"].str.cat(copy_9, sep ="**")
    
    #applying count to each for the frequency of each resource using coun
    df_input['google']= df_input['concat_resource'].apply(lambda x: x.count('Google'))
    df_input['stackoverflow']= df_input['concat_resource'].apply(lambda x: x.count('overflow'))
    df_input['online']= df_input['concat_resource'].apply(lambda x: x.count('online'))
    df_input['discussion_board_general']= df_input['concat_resource'].apply(lambda x: x.count('Discussion'))
    df_input['posted_to_discussion_board']= df_input['concat_resource'].apply(lambda x: x.count('I posted'))
    df_input['read_posts_discussion_board']= df_input['concat_resource'].apply(lambda x: x.count('help from reading'))
    df_input['friends_outside_of_class']= df_input['concat_resource'].apply(lambda x: x.count('friends'))
    df_input['peers_from_class_general']= df_input['concat_resource'].apply(lambda x: x.count('peer'))
    df_input['peer_helped_own_version']= df_input['concat_resource'].apply(lambda x: x.count('own version'))
    df_input['peer_pair_programming']= df_input['concat_resource'].apply(lambda x: x.count('pair programming'))
    df_input['tutors']= df_input['concat_resource'].apply(lambda x: x.count('tutor'))
    df_input['Teaching_Assistants']= df_input['concat_resource'].apply(lambda x: x.count('TA'))
    df_input['explicitly_stated_no_resource']= df_input['concat_resource'].apply(lambda x: x.count('I did not seek help or work with anyone this week'))
    
    return df_input

In [ ]:
#getting the resource frequency for all students, NN students and NE students separately
# df_get_resources_nn = (df_res_frequency[df_res_frequency['native_bool']==False])
# df_get_resources_ne = (df_res_frequency[df_res_frequency['native_bool']])
df_res_from_weeks_all = get_res_frequency_from_weeks(df_res_frequency)
# df_res_from_weeks_ne = get_res_frequency_from_weeks(df_get_resources_ne)
# df_res_from_weeks_nn = get_res_frequency_from_weeks(df_get_resources_nn)

In [ ]:
#get cols needed from grades
df_grades_mini = df_grades[['Overall.weighted.course.percentage','Final.exam.percentage','DeID']]

# inner join is the default option so should be joining correclty
df_all_res_grades = pd.merge(left=df_grades_mini, right=df_res_from_weeks_all, left_on='DeID', right_on='id')

plt.rc('figure', figsize=( 7,4)  , dpi=200)
plt.rc('font', size=4)   # font size
plt.xlabel("Values on X axis")
sns.heatmap(df_all_res_grades.corr(), annot = True, cmap= 'coolwarm', square=True, linewidths=.5, vmin=-1, vmax=1)

### A. Slight negative correlation between TA, Tutor, and Native_bool

1.   List item
2.   List item



#  <a id='section_interview'> INTERVIEW QUESTIONS </a> 

[- Return](#toc) 



#### A set of potential interview questions to understand more about the struggles that non-native English speakers face within the CS classroom  

- Do you feel that you spend more time studying on CS classes outside of class than you do on other classes? Why or why not?  
- When you do spend time out of CS classes, what categories are the hardest for you? (Readings, assignments, etc.) 
- Out of these list of resources: Which one do you feel most comfortable and why, which one has been the most helpful? 

### Recommendations for Future Survey Questions
- What resource has been the most helpful for you? (Drawing from the choices of 'how did you seek help this week')
- Out of these list of resources: Which one do you feel most comfortable and why, which one has been the most helpful? 
- Including a description of the definition of race for the Native American race category might help decrease the number of students who mark "other," as they might not identify with the race categories listed. The U.S. gov definition is: "American Indian or Alaska Native. A person having origins in any of the original peoples of **North and South America (including Central America), and who maintains tribal affiliation or community attachment**." The bolded part of the statement is important because people from this part of the world typically do not refer to themselves as "American Indian or Alaskan Native" so stating that this category includes people ALL of North, Central, and South America is important. 
https://www.carleton.edu/ira/fed-race-ethnic/

[Return To Table of Contents](#toc)
